100-hours-a-week/8-team-kar98-luckeat-fe

src/components/map/StoreMarker.jsx
지도 페이지에서 가게 목록과 지도 위에 마커를 표시하고, 마커 클릭 시 가게 이름이 나타나며 해당 가게의 상세 페이지로 이동할 수 있도록 구현함.
1. 지도 페이지에 가게 목록을 불러와서 표시함.
2. 지도 위에 가게 위치에 맞는 마커를 추가함.
3. 마커 클릭 시 해당 가게의 이름이 표시되도록 구현함.
4. 가게 이름을 클릭하면 상세 페이지로 이동하도록 설정함.
변경 사항이 UI에 영향을 미치므로, 아래 스크린샷을 참고.
1. 지도 페이지에 정상적으로 가게 목록이 나타나는지 확인함.
2. 지도에 마커가 올바르게 표시되는지 테스트함.
3. 마커 클릭 시 가게 이름이 정상적으로 표시되는지 확인함.
4. 가게 이름 클릭 시 상세 페이지로 정상 이동하는지 테스트함.
추가적인 테스트나 코드 개선이 필요한 부분이 있으면 피드백 부탁드립니다.
=> 개선: 가게 마커 UI 개선 - 카카오맵 기본 파란색 마커로 변경, 선택 시 노란색 별표, 가게 이름 말풍선은 클릭 시에만 표시

.github/workflows/s3-deploy.yml, vite.config.js
브랜치(main/dev)에 따라 S3 버킷 내 서로 다른 폴더에 `index.html`이 저장되도록 배포 프로세스를 수정했습니다.  
또한, 운영환경과 개발환경을 구분하여 각각의 CloudFront 배포를 구성하고, 배포 후 자동으로 캐시 무효화가 이루어지도록 설정했습니다.
- Closes #42 
1. GitHub Actions 워크플로우에서 브랜치에 따라 `production`, `development` 환경 변수 설정
2. S3 버킷에 `build` 결과물을 브랜치에 따라 각각 다른 폴더(`luckeat-front/production`, `luckeat-front/development`)로 업로드
3. CloudFront 배포를 각각 분리하여 운영/개발 환경을 구성
4. 배포 완료 후 해당 환경의 CloudFront 캐시를 자동으로 무효화하도록 설정
- AWS S3, CloudFront 관련 IAM 권한 및 비밀 키는 GitHub Secrets에 등록된 값을 사용합니다.
- 배포 대상 디렉토리는 `build` 또는 `dist` 기준이며, 프로젝트 빌드 설정에 따라 유동적으로 대응합니다.
=> 42 feat 클라우드프론트 개발운영환경 분리/siena

src/components/store/CategoryList.jsx, src/pages/HomePage.jsx
메인페이지에서 가게 카테고리를 나타내는 이모티콘 필터링 버튼 클릭 시  
노란색으로 강조되도록 수정했고, '전체' 카테고리가 항상 기본 선택되도록 개선했습니다
**문제 원인**  
- 선택 상태 표시 로직 불완전: 카테고리 아이콘 선택 상태를 확인하는 로직이 불완전했고, 문자열과 숫자 타입 비교 시 오류 발생  
- '전체' 카테고리 선택 상태 처리 미흡: 기본 선택 상태임에도 시각적 표시가 명확하지 않았음  
**수정 내용**  
- `CategoryList.jsx`  
- `isAllSelected` 변수 추가하여 빈 문자열, null, undefined일 경우 '전체' 선택 처리  
- 각 카테고리 버튼의 `isSelected` 상태 로직 추가  
- '전체'와 일반 카테고리의 선택 처리 분리  
- 선택된 카테고리 텍스트와 아이콘에 노란색 배경 스타일 적용  
- `HomePage.jsx`  
- `selectedCategory` 상태 초기값을 빈 문자열('')로 설정하여 '전체'가 기본 선택되도록 함  
- `handleCategorySelect` 함수에서 같은 카테고리 재클릭 시 '전체'로 초기화되도록 로직 개선  
- `onSelectCategory`로 `handleCategorySelect` 전달하여 클릭 처리 일원화  
이러한 수정을 통해 현재 선택된 카테고리를 사용자에게 명확히 보여주고, UX를 개선했습니다  
- Resolves #45
1. `CategoryList.jsx`: 선택 상태 구분 로직 추가 및 스타일 적용  
2. `HomePage.jsx`: 기본 선택 상태 설정 및 카테고리 …
=> 카테고리 아이콘 필터 클릭 시 노란색 강조 및 전체 기본 선택 설정

src/api/apiClient.js, src/config/apiConfig.js, vite.config.js
직접 EC2주소를 사용해서 요청을 보내던 코드(인증서를 거치지않아서 요청이 거부됨)를 상대경로로 수정하였습니다.
상대경로를 통해 cloudfront를 거쳐 요청을 보내도록 구성하였습니다.
- Clouses #46 
1. modified:   src/api/apiClient.js
3. modified:   src/config/apiConfig.js
4. modified:   vite.config.js
상대경로 사용하도록 수정하였습니다.
없음
로컬에서 빌드테스트를 수행하였습니다.
=> fix: API 상대경로 사용

src/pages/HomePage.jsx
- 카테고리를 선택한 후 다른 페이지로 이동하거나 새로고침했을 때, 선택된 카테고리 상태가 초기화되어 풀리는 문제가 있었습니다.
- 세션 스토리지를 활용하여 카테고리 선택 상태를 유지하고 페이지 로드 시 자동으로 복원하도록 구현했습니다.
- closes #60 
- 카테고리 중식 선택 
- 새로고침 후 선택 사항 유지
=> feat: 카테고리 선택 유지

src/App.jsx, src/api/storeApi.js, src/pages/EditStorePage.jsx
- 가게 정보 수정 API 연동
- PUT /api/v1/stores/{store_id} 엔드포인트 연동
- 가게 이미지, 가게 소개, 연락처만 수정 가능하도록 구현
[가게 정보 수정 페이지]
=> 가게 정보 수정 API 개선 및 EditStorePage 추가

src/pages/StoreDetailPage.jsx
가게 상세 페이지의 시각적 구성 개선 및 평점 위치 조정 작업을 진행함  
기존 가게 기본정보에 표시되던 평점을 리뷰 섹션 하단으로 이동하고, 구글 리뷰와 별도 구분되도록 개선함  
또한 각 영역 사이의 구분선과 공간을 추가하여 정보 구조를 더 명확하게 표현함
1. 가게 기본정보에서 평점 항목 제거
2. 평점 항목을 리뷰 섹션 하단으로 이동
3. 구글 리뷰 평균과 자체 리뷰 평균 별도 관리 및 UI 반영
4. 사업자번호와 구글 리뷰 평균 사이에 여백 추가
5. '상품 정보'와 '기본 정보' 사이에 구분선 추가
6. '가게 소개'와 '리뷰' 사이에도 구분선 추가
1. 평점이 리뷰 섹션 하단으로 정상 이동되는지 확인
2. 구글 리뷰 평균 별점과 자체 리뷰 별점이 명확히 구분되는지 확인
3. 추가된 구분선 및 여백이 UI에 자연스럽게 반영되는지 확인
4. 레이아웃 깨짐이나 기타 스타일 충돌 없는지 점검
- 구글 리뷰는 외부 API 기반이므로, 자체 리뷰와 혼동되지 않도록 텍스트 및 위치 분리 적용
- 추후 리뷰 정렬 기능 추가 시 현재 구조 기반으로 확장 가능
=> 디자인 수정: 가게 상세 페이지 구분선 및 공간 추가, 구글 리뷰 위치 수정

src/components/common/ScrollTopButton.jsx, src/pages/HomePage.jsx, src/pages/StoreDetailPage.jsx
홈페이지와 가게 상세페이지에 있는 ‘위로 가기’ 버튼의 위치를 사용자의 시야와 편의성을 고려해 고정 및 정렬 조정
---
---
> 없음
---
- `2025-03-28`
---
> 없음
---
👀 **추가 설명이 필요한 경우, 아래에 자유롭게 작성해주세요!**
- 스크롤을 많이 내렸을 때도 항상 우측 하단에서 접근 가능하도록 배치  
- 브랜치명: `Feature/scroll top button`
=> [FE] 홈페이지 및 가게 상세페이지 스크롤 버튼 위치 조정

src/api/apiClient.js, src/config/apiConfig.js, vite.config.js
개발 환경과 운영 환경에서 다른 API URL을 사용하도록 설정을 변경했습니다. 
개발 환경에서는 CloudFront URL을, 운영 환경에서는 luckeat.net 도메인을 사용합니다.
- Closes #96
1. `src/config/apiConfig.js`: 환경에 따른 API URL 분리 설정
- 개발 환경: `https://dxa66rf338pjr.cloudfront.net/api/v1`
- 운영 환경: `https://luckeat.net/api/v1`
2. `vite.config.js`: 개발 서버 프록시 설정을 CloudFront URL로 변경
- target URL을 `https://dxa66rf338pjr.cloudfront.net`으로 수정
3. `src/api/apiClient.js`: axios 인스턴스의 URL 설정을 환경에 따라 다르게 처리하도록 수정
- 환경 변수에 따라 다른 도메인으로 요청이 전송되도록 수정
1. 개발 환경에서 API 요청 테스트
- `curl -v https://dxa66rf338pjr.cloudfront.net/api/v1/stores` 요청 성공
- 가게 목록 데이터 정상 반환 확인
2. 환경 변수 설정 확인
- `process.env.NODE_ENV`가 'development'일 때 CloudFront URL 사용
- `process.env.NODE_ENV`가 'production'일 때 luckeat.net URL 사용
3. 개발 서버 재시작 후 API 요청 테스트
- 가게 목록 조회 정상 작동 확인
- 다른 API 엔드포인트도 정상 작동 확인
- 개발 …
=> fix: 개발/운영 환경에 따른 API URL 분리 설정

src/components/map/StoreMarker.jsx, src/pages/HomePage.jsx, src/pages/MapPage.jsx, src/pages/StoreDetailPage.jsx
가게 상세 페이지 및 리스트에서 이미지가 항상 디폴트 이미지로만 표시되던 문제를 수정함  
가게별 실제 이미지가 있을 경우 정상적으로 표시되도록 조건 분기 및 로직을 개선함
1. 가게 이미지 렌더링 로직 수정
- 이미지 URL이 유효할 경우 해당 이미지 표시
- 이미지가 없거나 로딩 실패 시에만 디폴트 이미지 사용
2. 이미지 로드 오류 처리 개선 (`onError` 핸들러 사용 등)
1. 이미지가 있는 가게와 없는 가게 모두 테스트
2. 실제 이미지가 정상적으로 표시되는지 확인
3. 없는 경우 디폴트 이미지가 적용되는지 확인
4. 이미지 로딩 실패 상황에서도 UI가 깨지지 않도록 처리 확인
- 이미지 존재 여부 판단 로직은 `이미지 URL 유효성 + 로딩 오류 대비` 조건으로 구성됨  
- 디폴트 이미지는 `public` 또는 `assets` 경로에서 관리됨
=> fix: 스토어 이미지가 제대로 표시되도록 수정

.releaserc.json
semantic-release의 브랜치별 버전 태그 전략을 수정하여 main과 develop 브랜치에서 각각 다른 형식의 버전이 생성되도록 설정했습니다.
-Closes #15 
1. `.releaserc.json` 파일의 branches 설정 수정
- `main` 브랜치: 일반 버전 형식 사용 (예: `1.0.0` -> `1.0.1`)
- `develop` 브랜치: beta 태그 추가 (예: `1.0.0-beta` -> `1.0.1-beta`)
- 불필요한 `next` 브랜치 설정 제거
2. 브랜치별 버전 태그 전략 명확화
- `main` 브랜치에서는 정식 버전 번호만 사용
- `develop` 브랜치에서는 버전 번호에 `-beta` 접미사 추가
1. `main` 브랜치 버전 생성 테스트
- 예상 결과: `1.0.0` -> `1.0.1` -> `1.0.2`
2. `develop` 브랜치 버전 생성 테스트
- 예상 결과: `1.0.0-beta` -> `1.0.1-beta`
이 PR이 머지되면 semantic-release가 브랜치별로 다른 버전 태그 전략을 적용하여 자동으로 버전을 관리하게 됩니다. 이를 통해 개발 버전과 프로덕션 버전을 명확하게 구분할 수 있습니다.
=> fix: semantic-release 브랜치 설정 수정

src/pages/HomePage.jsx
‘전체 마감할인’ → ‘전체 가게 목록’으로 텍스트 변경
각 가게에 별점 UI 표시
가게목록에 공유수
- Closes #101 
‘전체 마감할인’ → ‘전체 가게 목록’으로 텍스트 변경
각 가게에 별점 UI 표시
가게목록에 공유수
로컬에서 확인
=> 메인 홈페이지 기능 및 UI 수정

.releaserc.json
semantic-release가 보호된 브랜치에서도 정상적으로 작동하도록 설정을 수정했습니다. `@semantic-release/git` 플러그인을 제거하여 보호된 브랜치에 직접적인 커밋 없이 태그와 GitHub Release만 생성하도록 변경했습니다.
- Resolves #15
1. `.releaserc.json` 파일 수정
- `@semantic-release/git` 플러그인 제거
- 보호된 브랜치에 직접 커밋하지 않도록 설정
- 기존의 커밋 분석, 릴리즈 노트, changelog, npm, github 플러그인은 유지
2. 브랜치별 버전 태그 전략 설정
- `main` 브랜치: 정식 버전 (예: `1.0.0`)
- `dev` 브랜치: beta 버전 (예: `1.0.0-beta`)
3. GitHub Actions workflow 설정 최적화
- 기본 `GITHUB_TOKEN` 사용
- 필요한 권한들(contents, issues, pull-requests) 설정
1. `dev` 브랜치 버전 생성 테스트
- PR 머지 시 GitHub Actions 실행
- beta 태그가 포함된 버전 생성 (예: `1.0.0-beta`)
- GitHub Release 생성 확인
2. Protected 브랜치 정책 준수 확인
- 직접적인 커밋 없이 태그와 Release만 생성
- 브랜치 보호 설정과 충돌하지 않음
이 PR이 머지되면 semantic-release가 보호된 브랜치 정책을 준수하면서도 자동으로 버전을 관리할 수 있게 됩니다. 직접적인 커밋 대신 태그와 GitHub Release만 생성하여 버전 관리의 안정성을 …
=> fix: @semantic-release/git 플러그인 제거

src/api/apiClient.js, src/api/uploadApi.js, src/config/apiConfig.js, vite.config.js
- 개발환경(dev)과 운영환경(main)의 API 요청 URL을 구분하여 관리할 수 있도록 환경변수 기반 설정 추가
- `.env` 파일을 사용한 로컬 개발 환경 설정 지원
- GitHub Actions에서 환경별 시크릿으로 환경변수 주입 가능하도록 구성
1. `import.meta.env.VITE_API_URL`을 통한 환경변수 접근 구현
2. 환경변수가 없을 경우 기본값으로 클라우드프론트 URL 사용
3. 하드코딩된 URL을 환경변수 기반 URL로 대체
4. Vite 설정에 환경변수 로드 기능 추가
1. 로컬에서 `.env` 파일에 `VITE_API_URL` 설정
2. 개발 환경에서는 클라우드프론트로, 운영 환경에서는 luckeat.net으로 요청 확인
- `.env` 파일은 `.gitignore`에 추가하여 저장소에 커밋되지 않도록 함
=> feat: 환경 변수에서 API URL을 로드하도록 수정

.github/workflows/s3-deploy.yml
GitHub Actions 워크플로우에서 환경별(개발/프로덕션) API URL을 분리하여 설정할 수 있도록 수정했습니다. 이를 통해 각 환경에 맞는 API 엔드포인트를 사용할 수 있게 됩니다.
- Resolves #121
1. GitHub Actions 워크플로우 파일에 환경별 API URL 설정 추가
- 프로덕션 환경: `VITE_API_URL_PROD` 시크릿 사용
- 개발 환경: `VITE_API_URL_DEV` 시크릿 사용
2. 빌드 단계에 `VITE_API_URL` 환경변수 전달 로직 추가
1. GitHub Actions 워크플로우 파일 문법 검증
- GitHub 저장소의 Settings > Secrets and variables > Actions에서 다음 시크릿들을 추가해야 합니다:
- `VITE_API_URL_PROD`: 프로덕션 환경의 API URL
- `VITE_API_URL_DEV`: 개발 환경의 API URL
- 프로젝트에서는 `import.meta.env.VITE_API_URL`을 통해 환경변수에 접근할 수 있습니다.
=> chore: 환경별 API URL 분리 설정 추가

src/pages/EditStorePage.jsx
- 빈 문자열일 경우 서버 유효성 검사를 통과하기 위해 공백 문자 하나를 전송하도록 수정
- 폼 데이터에 연락처가 없을 경우 기존 가게 정보의 연락처를 사용
- 둘 다 없는 경우 빈 문자열로 처리
- 설명과 연락처 입력 필드에서 required 속성 제거
- 리뷰 요약 정보 표시 부분의 코드 포맷팅 개선
=> feat: 가게 정보 수정 페이지에서 설명 및 연락처 처리 로직 개선

src/pages/EditProfilePage.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx
회원가입 및 로그인 페이지에서 **비밀번호 입력란에 한글이 입력되지 않도록 차단**하는 기능을 구현함  
영문, 숫자, 특수문자만 입력 가능하도록 제한하여 비밀번호 형식을 보장하고 보안성을 강화함
- (선택 사항) 관련 이슈가 있다면 여기에 작성
1. 회원가입/로그인 페이지의 비밀번호 입력란에 한글 입력 차단 로직 추가
2. 키보드 입력 시 `onKeyDown`, `onInput`, `onChange` 등으로 한글 필터링 처리
3. 영문/숫자/특수문자만 입력 허용 (정규식 기반 제어)
4. 모바일/PC 환경 모두에서 정상 동작 확인
1. 비밀번호 필드에 한글 입력 시 무시되거나 삭제 처리되는지 확인
2. 영문/숫자/특수문자는 정상 입력 가능한지 확인
3. iOS/Android 가상 키보드에서도 동일하게 동작하는지 테스트
4. 기존 로그인/회원가입 기능이 정상 작동하는지 회귀 테스트 수행
- 향후 보안 강화를 위해 대소문자, 숫자, 특수문자 조합 규칙도 적용 예정  
- 한글 입력 차단 방식은 추후 사용자 피드백에 따라 개선 가능
=>  비밀번호 입력 시 한글 입력 방지 기능 추가

src/pages/HomePage.jsx, src/pages/MapPage.jsx
가게 이름과 주소가 너무 길 경우 레이아웃이 깨지는 문제를 방지하기 위해  
**가게 이름과 주소를 각각 최대 20자까지만 표시하고 이후는 `...` 으로 생략** 처리함  
메인페이지와 지도페이지의 가게 목록 모두 동일한 기준을 적용함
- Resolves #138
1. 메인페이지 가게 목록에서 가게 이름과 주소를 각각 최대 20자로 제한
2. 지도페이지 가게 목록에서도 동일한 방식으로 처리
3. `text-overflow: ellipsis`, `overflow: hidden`, `white-space: nowrap` CSS 적용
4. 반응형 레이아웃에서도 텍스트 잘림 현상 없이 자연스럽게 보이도록 조정
1. 20자 이상의 가게 이름 및 주소가 '…'으로 생략되어 표시되는지 확인
2. 텍스트 생략으로 인한 UI 깨짐이 없는지 확인
3. 모바일 및 데스크탑 환경에서 모두 반응형 UI 정상 동작 확인
4. 툴팁 또는 전체 주소 표시 여부는 추후 논의로 반영 가능
- 텍스트 길이 제한은 추후 디자인 요구사항에 따라 조정 가능  
- 툴팁을 통한 전체 텍스트 노출 여부는 UX 측면에서 추가 검토 필요
=> 가게 이름과 주소를 각각 최대 20자로 제한

src/App.jsx, src/pages/StoreDetailPage.jsx
가게 상세 페이지에서 공유 링크 생성 시 API URL 사용 및 인증 경로 수정
- Closes #133 
1. 가게 상세 페이지 로그인 없이 접근가능
2. 공유 링크시 url 추가
3. [변경 내용 3]
직접 테스트
=> 가게 상세 페이지에서 공유 링크 생성 시 API URL 사용 및 인증 경로 수정

src/App.jsx, src/pages/BusinessPage.jsx, src/pages/UserReservationsPage.jsx
RESTful한 명명 규칙을 지키기 위해 기존에 사용 중인 `/reservations` 복수형 경로를 `/reservation` 단수형으로 통일
---
---
> 없음
---
- `2025-03-28`
---
> 없음
---
👀 **추가 설명이 필요한 경우, 아래에 자유롭게 작성해주세요!**
- API 명세 문서도 함께 업데이트 필요 시 별도 이슈 생성  
- 추후 POST/GET/DELETE 요청이 일관되게 동작하는지 테스트 필요
=> API 경로 명명 규칙 통일: /reservations → /reservation

src/pages/LoginPage.jsx, src/pages/SignupPage.jsx
이전에 변경되었던 네비게이션 바와 로그인/회원가입 페이지의 UI를 원래 디자인으로 되돌림  
레이아웃 깨짐 및 스타일 충돌 방지를 위해 기존 안정적인 형태로 복원함
1. 네비게이션 바 기존 디자인 및 위치로 복원
2. 로그인 / 회원가입 페이지 UI를 원래 스타일로 되돌림
3. 불필요한 임시 스타일 또는 테스트 코드 제거
1. 모든 페이지에서 네비게이션 바 정상 표시 확인
2. 로그인 / 회원가입 페이지 UI 정상 렌더링 확인
3. 모바일 환경에서 UI 깨짐 없는지 확인
=> 네비게이션 바 복원 및 인증 페이지 UI 원복

src/pages/EditProfilePage.jsx
회원정보수정페이지의 스크롤 오류를 해결하였습니다.
추가적으로 입력박스 간격을 조정하였습니다.
- Closes #177 
1. 페이지 스크롤 오류 수정
2. 입력박스 간격 조정
틀린그림찾기아님.ㅋ
로컬에서 테스트 완료했습니다.
=> 177 fe 회원정보수정 페이지 스크롤 오류 수정

src/pages/StoreReservationsPage.jsx
예약 확인 페이지의 연락처 정보칸을 삭제하고 제로웨이스트 손님 표시 UI를 개선했습니다. 
- Closes #153
1. 연락처 정보칸을 삭제했습니다.
2. 제로웨이스트 손님 표시 UI 변경
변수명 불일치로 undefined 뜨던 제로웨이스트여부를 수정하여 노출되도록하였습니다.
- 기존: 닉네임 아래 문장으로 표시 ("포장용기를 지참하는 손님분이에요!")
- 변경: 닉네임 옆에 뱃지 형태로 표시 (초록색 배경의 "제로웨이스트" 뱃지)
1. 제로웨이스트 손님의 예약 건에서 뱃지가 정상적으로 표시되는지 확인
2. 일반 손님의 예약 건에서는 뱃지가 표시되지 않는지 확인
추후에 회원가입시 연락처를 받아서 예약시 전달해주는 방향도 고려해보면 좋을것같스빈다.
=> style: 제로웨이스트 뱃지 UI 개선

src/pages/StoreDetailPage.jsx
가게 상세페이지 내 영업시간 표기 방식 개선을 위한 수정입니다.  
기존에는 백엔드에서 `\n` 문자열로 전달되던 영업시간 정보가 실제 줄바꿈되지 않아 가독성이 떨어졌습니다.  
이를 해결하기 위해 문자열 내 `\n`을 실제 줄바꿈으로 변환하여 표시되도록 변경했습니다.
---
- `StoreDetailPage.jsx` 내 영업시간 문자열 파싱 로직 수정 (`\n` → 실제 줄바꿈 처리)
- 줄바꿈이 적용된 상태에서 텍스트가 보기 좋게 표시되도록 스타일 확인
- 브랜치명: `feature/fix-store-hours-linebreak`
---
- 상세페이지 영업시간 표시 오류 개선 요청
---
> 줄바꿈 전/후 비교가 있다면 첨부
---
---
---
현재 브라우저에서 영업시간이 정상적으로 줄바꿈되어 표시되고 있습니다.  
변경사항 확인 후 머지 부탁드립니다!
=> 영업시간 표시 개선: \n 문자열을 실제 줄바꿈으로 변환

src/pages/HomePage.jsx
가게 상세페이지 내 영업시간 표기 방식 개선을 위한 수정입니다.  
기존에는 백엔드에서 `\n` 문자열로 전달되던 영업시간 정보가 실제 줄바꿈되지 않아 가독성이 떨어졌습니다.  
이를 해결하기 위해 문자열 내 `\n`을 실제 줄바꿈으로 변환하여 표시되도록 변경했습니다.
---
- `StoreDetailPage.jsx` 내 영업시간 문자열 파싱 로직 수정 (`\n` → 실제 줄바꿈 처리)
- 줄바꿈이 적용된 상태에서 텍스트가 보기 좋게 표시되도록 스타일 확인
- 브랜치명: `feature/fix-store-hours-linebreak`
---
- 상세페이지 영업시간 표시 오류 개선 요청
---
> 줄바꿈 전/후 비교가 있다면 첨부
---
---
---
현재 브라우저에서 영업시간이 정상적으로 줄바꿈되어 표시되고 있습니다.  
변경사항 확인 후 머지 부탁드립니다!
=> 카테고리 필터 개선: 전체 카테고리 선택 시 검색어 초기화 및 검색 기능 향상

src/pages/BusinessPage.jsx, src/pages/MyPage.jsx, src/pages/StoreDetailPage.jsx
- `StoreDetailPage.jsx`에 사업자 안내 모달 추가
- 사업자(SELLER)가 예약하기 버튼 클릭 시 안내 모달 표시
- 안내 메시지: "사업자 계정으로는 예약이 불가능합니다. 일반 사용자 계정으로 로그인해주세요."
- 로그인하기 버튼 클릭 시 자동 로그아웃 후 로그인 페이지로 이동
- `MyPage.jsx`: 사업자(SELLER) 접근 시 자동으로 사업자 페이지로 리다이렉션
- `BusinessPage.jsx`: 일반 사용자(BUYER) 접근 시 자동으로 마이페이지로 리다이렉션
1. 사업자 계정으로 로그인
2. 가게 상세 페이지에서 예약하기 버튼 클릭
3. 사업자 안내 모달이 표시되는지 확인
4. 로그인하기 버튼 클릭 시 로그아웃 후 로그인 페이지로 이동하는지 확인
5. 일반 사용자 계정으로 로그인하여 예약이 정상적으로 가능한지 확인
- 사업자 계정으로 예약 시도 시 적절한 안내 메시지 필요
- 사업자/일반 사용자 페이지 접근 제어 구현
=> feat: 사용자 역할에 따른 페이지 네비게이션 및 사업자 안내 모달 추가

src/components/products/ProductManagement.jsx, tailwind.config.js
럭키트 저장 실패 시 토스트 메시지가 모달 뒤에 가려지는 현상을 수정했습니다.
스크린샷 참고해주세요!
- Resolves #270
1. 토스트 메시지의 z-index를 100으로 수정하여 모달(z-index: 50) 위에 표시되도록 변경
2. tailwind.config.js에 z-index 관련 설정 추가 (60~100)
3. Prettier를 통한 코드 포맷팅 적용
1. 럭키트 관리 페이지에서 럭키트 등록/수정/삭제 시 토스트 메시지가 모달 위에 정상적으로 표시되는지 확인
2. 모달이 열린 상태에서도 토스트 메시지가 가려지지 않고 잘 보이는지 확인
3. 테스트 환경: MacOS, Chrome 브라우저
토스트 메시지의 z-index 값을 100으로 설정한 이유는 현재 사용 중인 가장 높은 z-index 값이 50(모달)이기 때문입니다. 
향후 더 높은 z-index가 필요한 컴포넌트가 추가될 경우 이 값을 조정할 수 있습니다.
해당 코드외에 수정사항(내용변경없음)은 lint format을 돌려서 그런겁니다..
=> style: 토스트 메시지 z-index 수정 및 코드 포맷팅

src/pages/EditProfilePage.jsx
닉네임 변경 시 즉시 반영되지 않는 문제를 해결했습니다. 기존에는 닉네임 변경 후 상태 업데이트가 지연되어 사용자 경험이 저하되었습니다.
- Closes #221
1. 닉네임 변경 즉시 반영을 위한 상태 관리 개선
- `nicknameSuccess` 상태 추가로 성공 메시지 관리
2. UI/UX 개선
- '요청이 성공적으로 처리되었습니다' 대신 초록색 헬퍼 텍스트로 성공 메시지 표시
- 닉네임 입력 필드 아래에 직관적인 피드백 제공
이전
이후
기존 코드에서 닉네임 변경이 즉시 반영되지 않았던 이유:
1. 상태 업데이트 순서 문제
- `setOriginalNickname`과 `setIsNicknameSame` 상태 업데이트가 비동기적으로 처리되어 UI 업데이트가 지연됨
- React의 상태 업데이트 배치 처리로 인한 렌더링 지연
1. 닉네임 변경 테스트
- 2~10자 사이의 유효한 닉네임으로 변경 시도
- 변경 즉시 UI에 반영되는지 확인
- 성공 메시지가 초록색으로 표시되는지 확인
2. 유효성 검사 테스트
- 2자 미만 또는 10자 초과 닉네임 입력 시 에러 메시지 표시
- 중복된 닉네임 입력 시 에러 메시지 표시
3. 상태 초기화 테스트
- 새로운 닉네임 입력 시 이전 성공 메시지가 초기화되는지 확인
=> fix: 닉네임 변경 즉시 반영되도록 수정

src/pages/StoreDetailPage.jsx
가게 상세 페이지의 주소 복사 기능의 UI를 개선하고, 주소 표시에서 '대한민국'을 제거했습니다.
- Resolves #258
1. 주소 복사 UI 개선
- 복사 아이콘을 표시하도록 수정
2. 주소 표시 개선
- 주소에서 '대한민국' 텍스트 자동 제거 기능 추가
3. 복사 성공 메시지 개선
- 화면 중앙에 고정된 위치로 표시
- 반투명 검은 배경과 흰색 텍스트로 가시성 향상
이전
이후
1. 주소 복사 기능 테스트
- 주소 클릭 시 클립보드에 복사되는지 확인
- 복사 성공 메시지가 표시되는지 확인
- 복사된 주소가 정확한지 확인
2. 주소 표시 테스트
- '대한민국'이 포함된 주소에서 자동으로 제거되는지 확인
- 주소가 없는 경우 '주소 정보 없음'이 표시되는지 확인
3. UI 테스트
- 복사 아이콘에 마우스를 올렸을 때 툴팁이 표시되는지 확인
- 호버 효과가 정상적으로 작동하는지 확인
주소 복사기능이 있다는 것을 이슈로 처음알았습니다..
=> 258 가게주소복사기능 UI개선

src/api/apiClient.js
Axios 인스턴스(apiClient)의 설정을 정리하고 불필요한 CORS 관련 헤더를 제거함으로써  
코드의 간결성과 네트워크 요청의 안정성을 개선한 PR입니다.
- Resolves #[이슈 번호를 입력해주세요]
1. **apiClient 설정 개선**
- 기존에 axios 인스턴스 생성 시 포함되어 있던 CORS 관련 헤더 제거:
```js
'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
'Access-Control-Allow-Headers': 'Content-Type, Authorization',
```
- 해당 헤더는 **서버에서 설정해야 의미 있는 값**이므로, 클라이언트에서 설정하는 것은 무효하며 혼동을 줄 수 있음
- `withCredentials: true` 설정은 상황에 따라 `false`로 수정 필요 (현재는 명시적으로 제거됨)
2. **불필요한 설정 제거로 인해 코드 가독성 향상 및 axios 요청 처리 간소화**
해당 사항 없음 (코드 구조 변경 및 설정 정리)
- 모든 API 요청 정상 동작 확인
- 브라우저 개발자 도구에서 `Access-Control-*` 헤더 제거 여부 확인
- 서버 CORS 설정과 충돌 없음 확인
- 클라이언트에서 CORS 관련 헤더를 설정하면 실제 요청에는 반영되지 않으며,  
브라우저가 서버로부터 받은 응답 헤더를 기준으로 CORS 정책을 판단함
- 따라서 클라이언트 측 코드에서는 해당 헤더들을 제거하고, 서버 설정만 …
=> fix: withCredentials 설정을 true로 변경하고 불필요한 Access-Control 헤더 제거

src/pages/MapPage.jsx
- 지도 페이지(`MapPage`)에서 전체 가게 데이터를 불러올 때 사용하는 API 요청을 개선했습니다.
- 기존 하드코딩된 `/api/v1/stores` 경로를 상수화된 `API_BASE_URL`을 사용하는 방식으로 변경했습니다.
- 페이지네이션 기본값(`page=0`, `size=1000`)을 명시적으로 추가하여 한 번에 최대 1000개의 가게 데이터를 가져올 수 있도록 최적화했습니다.
---
1. API 요청 경로를 상수(`API_BASE_URL`) 기반으로 동적으로 구성
// 변경 전
let apiUrl = '/api/v1/stores'
// 변경 후
let apiUrl = `${API_BASE_URL}/stores`
2.전체 가게 데이터를 한 번에 불러오기 위해 쿼리 파라미터 추가
params.append('size', '1000')
params.append('page', '0')
할인중인 가게만 필터링 옵션이 활성화된 경우 isDiscountOpen=true를 함께 추가
=> 지도 페이지 API 엔드포인트 수정: 모든 가게 데이터 한 번에 로드

src/pages/StoreDetailPage.jsx
상품 상태가 close거나 재고가 0일 시 재고수량 안보이도록 수정
- closes #344
크롬에서 테스트 완료
=> StoreDetailPage에서 남은 수량 표시 로직 개선: 제품이 열려있지 않거나 수량이 0일 경우 남은 수량 텍스트를 숨김

src/App.jsx, src/pages/BusinessPage.jsx, src/pages/EditStorePage.jsx, src/pages/NoRegisteredStorePage.jsx, src/pages/ProductManagementPage.jsx, src/pages/StoreReservationsPage.jsx
사업자 회원이 로그인했지만 등록된 가게 정보가 없는 경우,
- `/no-registered-store` 안내 페이지로 리디렉션되며
- "가게 등록을 위해 luckeatnet@gmail.com 으로 연락주세요"라는 문구를 보여줍니다.
- 뒤로가기로 비즈니스 페이지로 돌아가지 않도록 popstate를 활용하여 차단했습니다.
---
- Resolves #333
---
1. `NoRegisteredStorePage` 페이지 신규 생성
- 가게 미등록 상태 안내 메시지 및 이메일 링크 포함
- 뒤로가기 시 비즈니스 페이지로 강제 이동 처리
2. 주요 페이지 접근 시 가게 등록 여부 확인 로직 추가
- `BusinessPage`, `EditStorePage`, `ProductManagementPage`, `StoreReservationsPage` 등
- `getMyStore()` 호출 결과가 없거나 `store.id`가 없을 경우 `/no-registered-store`로 이동
3. 라우트 등록
```js
<Route path="/no-registered-store" element={<NoRegisteredStorePage />} />
=> 333 사업자 가입시 가게 승인을 기다려주세요 같은 안내문구가 필요함

src/pages/UserReservationsPage.jsx
예약 취소 후 토스트 메시지가 자동으로 사라지지 않는 이슈를 수정하고, 토스트 메시지 표시 시간을 3초에서 2초로 변경했습니다.
- Resolves #342
1. 예약 취소 후 토스트 메시지가 자동으로 사라지지 않는 이슈 수정
- `handleCancelReservation` 함수에서 `setToastMessage`와 `setShowToast`를 직접 호출하는 대신 `showToastMessage` 함수를 사용하도록 변경
- `showToastMessage` 함수는 토스트 메시지를 표시하고 2초 후에 자동으로 사라지도록 설정
2. 토스트 메시지 표시 시간 변경
- 토스트 메시지가 표시되는 시간을 3초에서 2초로 변경
- `showToastMessage` 함수의 `setTimeout` 타이머 값을 3000ms에서 2000ms로 수정
1. 예약 취소 기능 테스트
- 대기중 상태의 예약을 선택하고 취소 버튼을 클릭
- 예약 취소 확인 모달에서 "확인" 버튼을 클릭
- "예약이 취소되었습니다" 토스트 메시지가 표시되고 2초 후에 자동으로 사라지는지 확인
2. 예약 취소 실패 시나리오 테스트
- 네트워크 오류나 서버 오류 발생 시 "예약 취소에 실패했습니다" 토스트 메시지가 표시되고 2초 후에 자동으로 사라지는지 확인
- 토스트 메시지 표시 시간을 2초로 변경한 이유는 사용자 경험을 개선하기 위함입니다. 3초는 다소 길게 느껴질 수 있어 2초로 조정했습니다.
- `showToastMessage` 함수를 사용함으로써 토스트 메시지 표시 로직을 일관되게 유지할 수 있게 되었습니다.
=> fix: 예약 취소 후 토스트 메시지가 사라지지 않는 이슈 수정 및 표시 시간 2초로 변경

src/pages/StoreDetailPage.jsx
가게 상세 페이지의 탭 클릭 시 스크롤 동작과 인디케이터 이슈를 해결했습니다. (스크롤과 인디케이터가 맞지않는 이슈)
각 섹션의 제목이 잘 보이도록 스크롤 위치를 조정하고, 스크롤 중 탭 인디케이터가 잘못된 위치로 이동하는 문제를 수정했습니다.
- Closes #332
1. 탭 클릭 시 스크롤 동작 수정
- 각 섹션의 제목이 잘 보이도록 스크롤 위치 조정 (상단 100px 여백 추가)
- `mainContainerRef.scrollTo` 사용하여 스크롤 동작 개선
- 모든 탭(지도, 럭키트 정보, 가게 정보, 리뷰)에 대해 동일한 스크롤 로직 적용
2. 탭 인디케이터 이슈 해결
- `isScrolling` 상태를 추가하여 스크롤 애니메이션 중 탭 변경 방지
- 스크롤 위치 감지 로직 개선 (`offsetTop` 사용)
- 각 섹션의 위치를 정확하게 계산하여 탭 전환 안정성 향상
스크롤을 내릴 때 인디케이터도 변함
1. 각 탭 클릭 시 동작 테스트
- 지도 탭 클릭 → "위치 정보" 제목이 상단에 보이도록 스크롤
- 럭키트 정보 탭 클릭 → "럭키트 정보" 제목이 상단에 보이도록 스크롤
- 가게 정보 탭 클릭 → "기본 정보" 제목이 상단에 보이도록 스크롤
- 리뷰 탭 클릭 → "리뷰" 제목이 상단에 보이도록 스크롤
2. 스크롤 중 인디케이터 동작 테스트
- 지도 탭 클릭 시 인디케이터가 다른 탭으로 이동했다가 돌아오는 현상 해결 확인
- 리뷰 탭 클릭 시 인디케이터가 가게 정보로 이동했다가 돌아오는 현상 해결 확인
스크롤 이벤트와 탭 클릭 이벤트의 충돌을 해결하기 위해 `isScrolling` 상태를 …
=> fix: 탭 클릭 시 스크롤 동작 수정 및 인디케이터 이슈 해결

src/main.jsx
Sentry를 self-hosted 서버로 이관하고 관련 설정을 업데이트했습니다.
- Closes #371
1. Sentry SDK 설정 업데이트
- self-hosted 서버 DSN 설정
- 환경 변수를 통한 DSN 관리 구성
- browserTracingIntegration, replayIntegration 설정 업데이트
2. Sentry 트레이싱 설정 업데이트
- tracesSampleRate: 100% 캡처
- tracePropagationTargets: localhost, luckeat.com 도메인 설정
3. 세션 리플레이 설정 구성
- replaysSessionSampleRate: 10%
- replaysOnErrorSampleRate: 100%
1. 로컬 개발 환경에서 Sentry 초기화 확인
- 환경 변수 정상 로드 확인
- Sentry SDK 초기화 성공 확인
2. 에러 트래킹 테스트
- 테스트 에러 발생 시 Sentry 대시보드에서 정상적으로 에러 수집 확인
3. 환경 변수 설정 검증
- .env.development 파일을 통한 로컬 환경 설정 확인
- .gitignore에 환경 변수 파일 제외 설정 확인
self-hosted Sentry 서버 주소: sentry.yimtaejong.com
환경 변수는 GitHub Secrets에 `SENTRY_DSN`으로 설정되어 있으며, 빌드 시 `VITE_SENTRY_DSN`으로 주입됩니다.
=> feat: Sentry self-hosted 서버로 이관

src/main.jsx
이전 PR #372 에서 개발환경 url (https://dxa66rf338pjr.cloudfront.net/)을 추가하였습니다. 
아래 PR내용은 이전과 동일합니다.
---
Sentry를 self-hosted 서버로 이관하고 관련 설정을 업데이트했습니다. 개발 환경과 운영 환경 모두에서 에러 트래킹이 가능하도록 설정했습니다.
- Resolves #371
1. Sentry SDK 설정 업데이트
- self-hosted 서버 DSN 설정 (sentry.yimtaejong.com)
- 환경 변수를 통한 DSN 관리 구성 (VITE_SENTRY_DSN)
- browserTracingIntegration, replayIntegration 설정 업데이트
2. Sentry 트레이싱 설정 업데이트
- tracesSampleRate: 100% 캡처
- tracePropagationTargets 설정:
- localhost (로컬 개발)
- luckeat.com (운영 환경)
- dxa66rf338pjr.cloudfront.net (개발 환경)
3. 세션 리플레이 설정 구성
- replaysSessionSampleRate: 10%
- replaysOnErrorSampleRate: 100% (에러 발생 시)
1. 로컬 개발 환경 테스트
- 환경 변수 정상 로드 확인
- Sentry SDK 초기화 성공 확인
- 테스트 에러 발생 시 정상 수집 확인
2. 개발 환경 테스트 (dxa66rf338pjr.cloudfront.net)
- 에러 트래킹 정상 작동 확인
- 트레이싱 설정 적용 확인
3. 환경 변수 설정 검증
- …
=> feat: Sentry 개발 환경 URL 추가

.github/workflows/s3-deploy.yml, src/App.jsx, src/main.jsx, src/pages/StoreDetailPage.jsx
Sentry를 self-hosted 서버로 이관하고, 에러 모니터링 설정을 개선했습니다.
추가적으로 가게 상세조회 페이지에서 나타나는 불필요한 콘솔로그를 제거하였습니다.
- Closes #371
1. Sentry DSN을 self-hosted 서버로 변경
2. Sentry 도메인 설정 추가
- localhost:3000
- dxa66rf338pjr.cloudfront.net
- luckeat.com
3. Sentry 설정 개선
- debug 모드 비활성화
- Session Replay 설정 추가
- Performance Monitoring 설정 추가
1. 로컬 환경 테스트
- 런타임 에러 발생 시 Sentry 캡처 확인
- Promise 에러 발생 시 Sentry 캡처 확인
- React 렌더링 에러 발생 시 ErrorBoundary 동작 확인
2. 개발 서버 테스트 (dxa66rf338pjr.cloudfront.net)
- 실제 환경에서 에러 캡처 동작 확인
- ErrorBoundary 폴백 UI 표시 확인
- Sentry self-hosted 서버: https://sentry.yimtaejong.com
- 에러 발생 시 Sentry 대시보드에서 확인 가능
개발자도구에서 확인되는 콘솔로그 제거하였습니다.
=> 371 센트리 self hosted 로 이관
