.github/workflows/semantic.yml

태그 생성 테스트
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]

feat: Semantic Release 태그 생성 테스트

---

.releaserc.json
CHANGELOG.md
commitlint.config.cjs
package-lock.json
package.json

1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]

feat: semantic-release 테스트

---

.idea/.gitignore
.idea/8-team-kar98-luckeat-fe.iml
.idea/checkstyle-idea.xml
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/misc.xml
.idea/modules.xml
.idea/prettier.xml
.idea/vcs.xml
src/api/apiClient.js
src/api/userApi.js
src/components/layout/Header.jsx
src/config/apiConfig.js
src/context/AuthContext.jsx
src/pages/HomePage.jsx
src/pages/LoginPage.jsx

- API 요청 경로 수정
- API 엔드포인트에서 중복된 '/v1/' 접두사 제거
- 올바른 API 요청 경로 구성으로 오류 해결
- 로그인 성공 시 사용자 정보 및 토큰 관리 개선
- accessToken과 refreshToken 별도 저장
- 사용자 정보(userId, email, nickname, role) 저장
- 로그인 후 메인 페이지로 자동 리다이렉션
- 새로고침 시 로그인 상태 유지
- 로컬 스토리지를 활용한 인증 상태 보존
- 새로고침 시 사용자 정보 및 로그인 상태 유지
- 선택적으로 백엔드 API로부터 최신 사용자 정보 조회
- 로그인 상태에 따른 조건부 헤더 UI 표시
- 로그인 상태: "로그아웃" 버튼만 표시
- 비로그인 상태: "로그인 | 회원가입" 버튼 표시

feat: 로그인 구현, 유저 정보 및 토큰은 로컬스토리지에 저장

---

package.json
src/api/userApi.js

로그아웃 시 
- jwtd토큰 헤더에 담아서 API요청 보내도록 구현
- 로컬스토리지 비움

feat: 로그아웃 기능 구현

---

src/api/apiClient.js
src/api/storeApi.js
src/api/userApi.js
src/pages/HomePage.jsx
src/pages/StoreDetailPage.jsx

가게 상세페이지 구현
- 가게 정보 및 해당 가게의 상품정보 보여줌

가게 상세페이지 구현

---

src/api/apiClient.js

- 마이페이지에서 인증되지 않는 문제가 발생하여 **토큰을 헤더에 추가**함  
- 기존에 **더미 데이터**로 동작하던 마이페이지를 **백엔드와 완전히 연동**하여 실데이터를 불러오도록 수정함  
---
---
1. 마이페이지 API 요청 시 **Authorization 헤더에 토큰 추가**  
2. **더미 데이터를 제거**하고 백엔드 API와 연동하여 실데이터를 불러오도록 변경  
3. API 응답 데이터에 맞춰 **프론트엔드 데이터 처리 로직 수정**  
---
---
1. **로그인 후 마이페이지 접속** 시 정상적으로 데이터를 불러오는지 확인  
2. **토큰 없이 마이페이지 접근 시 인증 오류 발생 여부 확인**  
3. **데이터 수정 후 마이페이지에서 즉시 반영되는지 확인**  
---
---
- API 응답 형식이 변경될 가능성이 있어, 추후 **백엔드 API 문서**를 확인 후 추가 수정이 필요할 수 있음.  
- 인증 관련 테스트는 **로컬 및 개발 서버 환경에서 검증 완료**함.

Fix token authentication in API client

---

src/api/reviewApi.js
src/pages/EditProfilePage.jsx
src/pages/MapPage.jsx
src/pages/MyPage.jsx
src/pages/ReviewManagementPage.jsx

1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]

전체 로컬 변경사항 커밋

---

src/api/storeApi.js
src/components/map/StoreMarker.jsx
src/pages/HomePage.jsx

마감할인중만 필터적용 

---

src/api/reviewApi.js
src/pages/EditProfilePage.jsx
src/pages/MapPage.jsx
src/pages/MyPage.jsx
src/pages/ReviewManagementPage.jsx
src/pages/StoreDetailPage.jsx

가게 상세페이지에서 가게별 리뷰를 보여주도록 구현 완료

feat: 가게 상세페이지 리뷰

---

.github/workflows/s3-deploy.yml
vite.config.js

프론트엔드 배포 프로세스 개선을 위한 워크플로우 수정
- Closes #26 
1. CloudFront 캐시 무효화 기능 추가
2. GitHub Actions 워크플로우에 CloudFront 캐시 무효화 단계 구현
3. react-kakao-maps-sdk 관련 번들링 문제 확인
해당 없음
해당 없음

26 refactoring s3 deployyml 수정/siena

---

.github/workflows/s3-deploy.yml
src/pages/HomePage.jsx
src/pages/MapPage.jsx

- 메인페이지 가게 평균 별점 보이도록 수정
- 별점 높은 순 정렬 구현 (별점이 같을 시 공유 순으로 정렬)

메인페이지 평균 별점 및 정렬 구현

---

.github/workflows/s3-deploy.yml
src/api/userApi.js
src/context/AuthContext.jsx
src/pages/SignupPage.jsx
src/utils/apiMessages.js

회원가입 성공 시 나타나는 모달창이 나타나지 않는 문제를 해결했습니다
**문제 원인**  
- API 응답 처리 오류: 서버가 201 상태 코드를 반환했지만 클라이언트에서 이를 제대로 처리하지 못함  
- 성공 상태 확인 로직 오류: `AuthContext.jsx` 내 로직이 불완전함  
- 로그 메시지 오류: 성공을 실패로 잘못 판단하는 로그 메시지 출력됨  
**수정 내용**  
- `apiMessages.js`: `handleSuccessResponse` 수정  
- `AuthContext.jsx`: `signup` 함수 수정 및 디버깅용 로그 추가  
- `SignupPage.jsx`: 성공 응답 처리 및 모달 표시 로직 개선  
- `userApi.js`: 요청 및 응답 로깅 추가
- Resolves #123
1. 응답 처리 로직 수정 (`apiMessages.js`)
2. 상태 코드 확인 및 리턴 로직 개선 (`AuthContext.jsx`)
3. 성공 모달 표시 조건 수정 (`SignupPage.jsx`)
4. 디버깅용 로그 추가 (`userApi.js`)
_(해당 없음)_
1. 정상적인 회원가입 후 성공 모달 표시 확인  
2. 201 상태 응답 로그 출력 확인  
3. 실패 케이스에서 모달 미표시 확인  
- API 응답 구조 표준화 필요 여부 논의 예정

회원가입 성공 시 모달이 표시되지 않던 문제 수정

---

.github/workflows/s3-deploy.yml
src/config/apiConfig.js
vite.config.js

정적 파일을 제공하는 도메인 요청을 HTTPS 프로토콜로 변경했습니다.  
+ 개발/운영 환경 분리를 위해 s3버킷 구조를 아래와같이 생성되도록 변경했습니다.
```
s3://luckeat-front/
├── development/   # dev 브랜치일 때
│    ├── index.html
│    └── assets/
└── production/    # main 브랜치일 때
├── index.html
└── assets/
```
- Closes #29 
1. 정적 리소스를 불러오는 URL을 HTTP에서 HTTPS로 변경
2. HTTPS를 기본으로 사용하도록 배포 환경 설정 수정
3. 개발/운영환경 분리를 위해 파일구조 분리
로컬에서 빌드테스트를 완료했습니다.
(파일구조 확인완료)

fix: Mixed Content error

---

src/api/apiClient.js
src/api/storeApi.js
src/api/uploadApi.js
src/api/userApi.js

로컬스토리지에서 jwt토큰을 accessToken, Token 두 키에 담는 오류가 있어 수정하였음

로컬스토리지에서 중복 된 token 삭제

---

src/api/apiClient.js
src/api/categoryApi.js
src/api/permissionApi.js
src/api/productApi.js
src/api/reviewApi.js
src/api/storeApi.js
src/api/userApi.js
src/config/apiConfig.js

- API 접두사를 `/api`로 통일하여 프록시 설정과 일치시킴  
- 모든 API 경로에 `/v1/...` 구조를 적용하여 백엔드 명세서와 일치시킴  
- API 서버 주소를 HTTP로 통일하여 로컬 프록시 및 배포 환경과 충돌 없도록 설정  
- `getStores` 함수의 URL 생성 방식을 백엔드 명세서에 맞춰 개선
- `luckeat.net`에서 가게 목록이 정상적으로 표시되지 않는 문제 해결
- 백엔드 서버가 실행 중인 상태에서 전체 API 요청 흐름 테스트  
- 홈 화면에서 가게 목록이 정상적으로 조회되는지 확인  
- 관련 리뷰, 상세 페이지 등 데이터 호출이 일관되게 동작하는지 확인
- Resolves #78  
1. `api/index.js`: 기본 경로를 `/api`로 수정 및 `/v1` 포함하도록 전면 수정  
2. `storeApi.js`: `getStores` 함수에서 URL 동적 생성 방식 개선  
3. `vite.config.js` 또는 프록시 설정: `/api`로 프록시 경로 맞춤  
_(해당 없음)_
1. 가게 목록 조회 시 정상 응답 여부 확인  
2. 프론트에서 호출하는 모든 API가 `/api/v1/...` 형식으로 전송되는지 확인  
3. 배포 환경에서도 `luckeat.net`에서 목록 표시 문제 해결됨을 확인
- 향후 API 버전(`/v2` 등) 변경에 대비해 prefix 구조를 더 유연하게 구성할 필요 있음

fix: API 경로 및 접두사 수정으로 가게 목록 조회 문제 해결

---

src/components/store/CategoryList.jsx
src/pages/EditProfilePage.jsx

- 리뷰관리 페이지와 회원정보 수정 페이지의 레이아웃을 정리했습니다  
- 백엔드 API 명세를 참고하여 데이터 연동 로직을 수정했습니다  
- UI와 기능이 자연스럽게 연결되도록 정리했습니다
1. `ReviewManagePage.jsx`: 리뷰관리 레이아웃 정리 및 API 연동 로직 추가
2. `EditProfilePage.jsx`: 회원정보 수정 페이지 레이아웃 수정 및 데이터 처리 개선
3. 공통 컴포넌트 일부 수정하여 API 응답 포맷에 맞게 적용
_(해당 변경 사항이 있는 경우 스크린샷 첨부)_
1. 리뷰 목록 정상 로딩 확인 
2. 회원정보 수정 후 레아이웃확인
3. 닉네임 변경, 비밀번호 변경, 탈퇴 기능 테스트
- 현재 API 스펙이 일부 변경될 가능성이 있어, 이후 리팩토링 여지 있음  
- UI/UX 개선 포인트는 다음 PR에서 추가 반영 예정

리뷰관리 & 회원정보 수정 페이지 레이아웃 정리 및 API 연동

---

src/pages/HomePage.jsx

- 메인페이지에서 가게별 리뷰개수 보이도록 구현 
- 리뷰 많은 순 정렬 구현

feat: 메인페이지에서 리뷰수 노출 및 리뷰많은 순 정렬 구현

---

src/api/apiClient.js
src/api/categoryApi.js
src/api/permissionApi.js
src/api/productApi.js
src/api/reviewApi.js
src/api/storeApi.js
src/api/userApi.js
src/config/apiConfig.js
src/pages/MapPage.jsx
vite.config.js

도메인 주소가 실제 서버와 일치하지 않는 부분들을 수정했습니다  
API 요청이 정상적으로 전송되지 않던 문제를 해결하기 위해 올바른 도메인 주소로 전면 정비했습니다
1. API 요청 base URL을 `.env` 파일의 환경변수로 설정하고 일관되게 적용  
2. 테스트용 도메인을 운영 도메인(`https://luckeat.net`)으로 수정  
3. 프록시 설정 경로에 맞게 API 경로 일부 재정비
_(도메인 변경은 UI 변화가 없으므로 첨부 생략)_
1. 배포 서버에서 실제 도메인 기준 데이터 정상 표시 확인  
2. 잘못된 도메인 주소가 포함된 요청이 더 이상 발생하지 않는지 확인

fix: 도메인 주소 불일치 문제 수정

---

src/App.jsx
src/context/AuthContext.jsx
src/pages/LoginPage.jsx
src/utils/jwtUtils.js

- JWT 페이로드에서 만료 시간을 추출하여 토큰 유효성 검사 유틸리티 추가
- 앱 시작 및 라우트 변경(페이지 이동) 시 토큰 유효성 자동 검증 
- 만료된 토큰 발견 시 자동 로그아웃 및 로그인 페이지 리다이렉션
- 세션 만료 메시지 표시 기능 추가
- closes #59 
- JWT 토큰 만료 시 토큰 삭제 및 안내 메시지와 함께 로그인 페이지로 자동 리다이렉션

feat: JWT 토큰 만료 검사 및 자동 로그아웃 기능 구현

---

.env.development
.github/workflows/s3-deploy.yml
.gitignore
index.html
package.json
src/App.jsx
src/main.jsx
src/pages/HomePage.jsx

사용자 행동분석 및 이슈 모니터링을 위한 google analytics, sentry를 적용하였습니다.
Microsoft Clarity 의 경우 위 두 가지와 역할이 겹쳐 제외해도 괜찮다고 판단하였습니다.
- Closes #58 
1. index.html 에 ga를 위한 코드를 추가했습니다.
2. sentry 적용을 위해 일부 코드를 수정하였습니다.
없음
1. npm run dev 로 개발환경에서 sentry 테스트를 완료했습니다.
2. npm run build 로 컴파일 오류가 없음을 확인했습니다.

58 google analytics, sentry 적용

---

.husky/commit-msg
.husky/pre-commit

chore: 커밋 메시지 체크 및 자동 포맷팅 비활성화

---

src/components/layout/Header.jsx
src/pages/HomePage.jsx

헤더와 홈페이지에 표시되는 "Luckeat" 텍스트를 서비스명 "제빵사"로 변경함  
서비스 방향성에 맞는 용어로 통일하기 위한 UI 텍스트 수정 작업
1. `src/components/layout/Header.jsx` - 21번 줄 텍스트 "Luckeat" → "제빵사"
2. `src/pages/HomePage.jsx` - 250번 줄 텍스트 "Luckeat" → "제빵사"
3. `feature/change-header-text` 브랜치 생성 후 변경사항 커밋 및 원격 푸시
UI 텍스트만 변경되어 시각적 변화가 크지 않아 스크린샷은 생략함
1. 로컬 서버 실행 후 변경된 텍스트가 정상적으로 렌더링되는지 확인함
2. 브라우저에서 헤더 및 홈페이지에서 "제빵사" 문구 확인 완료
3. 원격 저장소에 브랜치 푸시 후 dev 브랜치로 복귀 확인
기능 변경 없이 UI 텍스트만 변경된 단순한 수정사항입니다  
서비스명 리뉴얼에 맞춘 전처리 작업으로, 이후 다른 페이지에도 동일한 변경이 적용될 예정입니다

style: 앱 이름 'Luckeat'을 '제빵사'로 변경

---

src/App.jsx
src/pages/BusinessPage.jsx

사업자 페이지 구현
- /business 로 사업자 페이지 이동가능
- [상품정보 수정]: 클릭시 /edit-product 로 이동
- [가게 정보 수정]: 클릭시  /edit-store 로 이동
- [로그아웃]: 클릭시 로그아웃

feat: 사업자 페이지 구현

---

src/api/storeApi.js
src/components/store/StoreCard.jsx
src/pages/BusinessPage.jsx

feat: 사업자 페이지 가게정보 추가

---

src/pages/HomePage.jsx

메인페이지 UI를 개편하기 위한 작업을 진행함  
카테고리 버튼 제거, 위치 기반 필터링 버튼 추가, 카드뉴스 섹션 및 다양한 콘텐츠 카드 컴포넌트를 도입하여 사용성 개선을 목표로 함
1. 메인페이지에서 기존 카테고리 버튼 제거
2. '내 주변', '지역 선택' 등의 위치 기반 필터링 버튼 UI 컴포넌트 추가
3. 메인화면 상단에 카드뉴스 형태 섹션 추가
4. 소개 페이지용 콘텐츠 카드 추가
5. 프랜차이즈 메뉴 중 '제주도 한정' 콘텐츠 카드 추가
6. 제빵사 로고 카드 컴포넌트 추가
(예: 메인페이지 상단 카드뉴스, 각 콘텐츠 카드의 레이아웃 등)
1. 로컬 서버 실행 후 각 카드 및 버튼이 정상 렌더링되는지 확인
2. 버튼 클릭 시 UI 반응 확인
3. 반응형 레이아웃에서 각 요소가 깨지지 않는지 테스트
4. 크로스 브라우저 테스트 (Chrome, Safari 등)
- 위치 기반 필터링 기능은 UI만 구현되어 있으며 실제 위치 데이터 연동은 추후 작업 예정
- 카드 컴포넌트는 재사용 가능하도록 설계됨 (소개/제주도 한정/로고)

메인페이지 ui 수정

---

src/pages/StoreDetailPage.jsx

지도 페이지에서 지도가 표시되지 않던 문제를 해결하고, 전반적인 UI를 개선함  
지도 API 로딩 처리 및 시각적 안정성을 보완하고, 별점 및 섹션 레이아웃을 조정하여 사용자 경험 향상
1. 카카오맵 API가 로드되지 않던 문제 해결
- 카카오맵 스크립트를 직접 `<script>` 태그로 로드
- 환경 변수에서 API 키를 가져와 동적으로 삽입
- `window.kakao?.maps` 조건문을 통해 API 로딩 여부 확인
2. 지도 UI 개선
- 지도가 표시되지 않는 동안 "지도 정보를 불러오는 중..." 메시지 표시
- 지도 컨테이너에 배경색 추가하여 로딩 중 시각적 피드백 제공
- 지도가 로드될 때 콘솔 디버깅 메시지 추가
3. 전체 UI 조정
- 별점 영역 텍스트 크기 및 여백 축소
- 섹션 간 간격 축소 (`p-4` → `p-3`, `space-y-4` → `space-y-3`)
- 이미지 로드 실패 시 `style.display = 'none'` 처리 추가
1. `.env` 파일의 `VITE_KAKAO_MAP_API_KEY` 값을 기반으로 API 정상 로드 확인
2. 로컬 서버에서 지도 표시 확인 (`window.kakao.maps` 존재 여부 디버깅)
3. 로딩 메시지와 배경색 처리 정상 동작 확인
4. 별점 영역 UI 정상 축소 여부 확인
5. 이미지 로드 실패 시 해당 영역이 자연스럽게 숨겨지는지 확인
- 카카오맵 API 키는 `.env` 환경 변수로 외부 노출 방지
- 지도 로딩 실패나 이미지 에러가 발생할 경우에도 UX가 크게 …

지도 표시 문제 해결 및 UI 개선

---

package.json
src/App.jsx
src/api/productApi.js
src/api/uploadApi.js
src/components/products/ProductManagement.jsx
src/components/store/StoreCard.jsx
src/pages/BusinessPage.jsx
src/pages/ProductManagementPage.jsx

- 상품 관리 페이지 컴포넌트 추가
- 상품 등록, 수정, 삭제 기능 구현
- 상품 목록 조회 및 상태 변경(is_open) 기능 추가

feat: 상품 관리 페이지 및 관련 API 추가

---

index.html
src/App.jsx
src/components/layout/Header.jsx
src/components/layout/Navigation.jsx
src/index.css
tailwind.config.js

앱 전체 페이지의 레이아웃을 정비하고, 웹뷰 상단 및 배경 색상을 적용하여 UI/UX 통일성 확보  
공통 스타일을 점검하고, 시각적 일관성을 위한 주요 색상 조정 수행
- Resolves #84
1. 전체 페이지 레이아웃을 동일한 그리드/마진 기준으로 통일
2. 웹뷰 상단 (상태바 포함) 영역에 공통 배경 색상 적용
3. 버튼, 배경, 텍스트 등 주요 UI 요소의 색상 정리 및 수정
4. 디자인 시스템 기준에 맞춘 공통 스타일 반영 여부 점검 및 적용
1. 모든 주요 페이지에서 공통 레이아웃 및 색상 적용 확인
2. 기존 스타일 충돌 여부 확인 및 디버깅 완료
- 공통 레이아웃과 색상은 디자인

디자인 개선: 홈페이지 위치 아이콘 및 전체 UI 스타일 업데이트

---

src/pages/MyPage.jsx

마이페이지의 유저 프로필 사진 영역과 전체 UI를 개선함  
프로필 이미지 업로드, 표시 방식 개선 및 시각적 구성 정리를 통해 사용자 경험을 향상시킴
1. 마이페이지 상단 유저 프로필 사진 UI 수정
2. 기본 이미지 또는 업로드된 이미지가 동그란 형태로 표시되도록 스타일 개선
3. 프로필 이미지 변경 버튼 UI 개선 (마우스 hover 시 아이콘 또는 버튼 표시)
4. 전체 마이페이지 레이아웃 및 마진, 정렬 재조정
5. 모바일 뷰에서도 이미지와 레이아웃이 깨지지 않도록 반응형 대응
1. 기본 프로필 이미지 및 업로드된 이미지 모두 정상 렌더링 확인
2. 프로필 이미지 변경 버튼 hover 시 UI 정상 작동 확인
3. 다양한 화면 너비에서 반응형 UI 확인
4. 마진/패딩 변경에 따른 레이아웃 흐름 테스트
- 추후 프로필 사진 변경 시 실제 이미지 업로드 및 서버 반영 로직은 별도 구현 예정
- 마이페이지의 다른 UI 요소들도 순차적으로 리팩토링 예정

마이페이지 텍스트 및 프로필 이미지 수정

---

src/api/storeApi.js
src/pages/EditStorePage.jsx

feat: 사업자 페이지 및 가게 정보 수정 페이지 리팩토링

---

src/pages/StoreDetailPage.jsx

이미지 표시 부분 개선:
가게 이미지 로딩 시 더 유연한 처리 방식 적용
store.storeImg ? store.storeImg : (store.imageUrl || defaultImage) 형태로 이미지 소스 우선순위 설정
구글 이미지 URL 처리 로직 추가:
Google Maps API 이미지 URL 감지 함수 추가
구글 이미지 로드 실패 시 가게 이름 특성에 맞는 기본 이미지 표시
별점 표시 통일:
모든 별점 표시 부분에서 avgRatingGoogle 사용
리뷰 섹션에서도 구글 평점으로 통일
이미지 로드 실패 대응 강화:
이미지 미리 로드 시도 로직 추가
오류 발생 시 대체 이미지 표시 및 로그 기록
구글 리뷰 평균 별점 섹션 개선:
가게 설명 문구 제거하고 깔끔한 UI로 변경
공유 기능 개선:
공유 URL에 storeUrl 우선 사용
공유 시 공유 카운트 증가 API 호출 추가
오류 처리 강화:
이미지 로드 오류, API 응답 오류 등에 대한 예외 처리 개선
디버깅 로그 추가
이 변경사항들로 인해 가게 상세 페이지가 더 안정적으로 작동하고, 이미지 로딩 문제에 더 강건하게 대응할 수 있게 되었습니

feat: 가게 상세보기 페이지 수정

---

src/pages/StoreDetailPage.jsx

- 상세 페이지에서 공유 버튼 클릭시 서버로 공유수 증가 요청을 보내는 로직 삭제
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]

fix: 공유증가 로직 삭제

---

src/api/storeApi.js
src/components/layout/Navigation.jsx
src/pages/EditStorePage.jsx

- 가게 정보 수정 API 업데이트
- PUT /api/v1/stores/{store_id} 엔드포인트 사용으로 변경
- 신규 필드(avgRating, avgRatingGoogle, googlePlaceId) 추가
- 수정 시 기존 정보를 모두 포함하도록 요청 구조 개선
- 사용자 역할 기반 네비게이션 수정
- 'SELLER' 역할 사용자는 마이페이지 버튼 클릭 시 사업자 페이지('/business')로 자동 이동
- 일반 사용자는 기존대로 마이페이지('/mypage')로 이동
- 네비게이션 활성화 상태 표시 개선 (마이페이지, 사업자 페이지 모두 반영)
가게 정보 수정 오류 해결 및 role에 따라 마이페이지 리다이랙션
크롬에서 테스트 완료

Feature: 가게 정보 수정 오류 개선 및 

---

src/pages/HomePage.jsx

홈페이지 스크롤 시 가게 목록 페이징 기능 추가 및 초기 표시 가게 목록 업데이트 로직 구현
- Closes #116 
홈페이지 스크롤 시 가게 목록 페이징 기능 추가 및 초기 표시 가게 목록 업데이트 로직 구현

홈페이지 스크롤 시 가게 목록 페이징 기능 추가 및 초기 표시 가게 목록 업데이트 로직 구현

---

src/pages/HomePage.jsx

[구현 내용]
- 카테고리를 처음 클릭하면 해당 카테고리가 선택됩니다.
- 이미 선택된 카테고리를 다시 클릭하면 선택이 취소됩니다.
- 다른 카테고리를 클릭하면 이전 선택이 취소되고 새로운 카테고리가 선택됩니다.
- closes #128 
- 크롬에서 테스트 성공

홈페이지에서 위치 선택 기능 개선: 동일한 위치 선택 시 필터 초기화 로직 추가

---

src/components/layout/Navigation.jsx

내비게이션바(Navigation Bar)의 UI를 정돈하고 아이콘 중심의 디자인으로 변경함  
글자(label)를 제거하고, 전체 크기를 조정하여 깔끔한 하단 메뉴 구성으로 개선
1. 내비게이션바에서 각 메뉴 아이콘에 표시되던 글자 제거
2. 내비게이션바 전체 높이 및 아이콘 크기 조정
3. 아이콘 중심 UI로 변경하여 시각적으로 단순하고 직관적인 구성으로 개선
1. 각 아이콘 클릭 시 해당 페이지로 정상 이동되는지 확인
2. 글자 제거 후에도 UX에 지장이 없는지 확인
3. 아이콘 사이 간격 및 전체 크기 변경에 따른 레이아웃 테스트
4. 모바일 환경에서 하단 고정 및 터치 정확도 확인
- 향후 선택된 아이콘에 대한 강조(색상 변경 또는 배경 효과) 추가 예정
- 사용자 테스트를 통해 글자 제거에 대한 피드백 반영 가능성 있음

내비게이션바(Navigation Bar)의 UI

---

src/components/common/ScrollTopButton.jsx
src/components/map/MapController.jsx
src/components/map/StoreMarker.jsx
src/index.css
src/pages/MapPage.jsx
src/pages/StoreDetailPage.jsx

지도에서 마커 클릭 시 표시되는 인포윈도우의 UI를 개선함  
세로 크기를 절반 수준으로 축소하고, 버튼 위치를 조정하여 사용자 시인성과 조작성을 높임  
마커 디자인은 기존 스타일을 유지
카카오 길찾기 현재위치가 뜨도록 변경
1. 인포윈도우(말풍선)의 세로 길이를 약 50% 축소
2. 버튼 위치를 오른쪽 하단 등 적절한 영역으로 조정
3. 기존 마커 디자인은 변경 없이 유지
4. 콘텐츠 내용에 따라 인포윈도우 내부 레이아웃 조정
5. 인포윈도우에서 카카오 길찾기 버튼 삭제
1. 다양한 해상도에서 인포윈도우가 정상적으로 축소된 크기로 표시되는지 확인
2. 버튼 클릭 영역이 겹치거나 가려지지 않는지 테스트
3. 마커 클릭 시 인포윈도우 위치와 방향 정상 표시 여부 확인
4. 여러 개의 인포윈도우 동시 표시 시 UI 충돌 여부 확인
- 인포윈도우 크기 축소로 인해 콘텐츠가 잘리는 경우는 line-clamp 등으로 대응  
- 필요시 모바일 전용 스타일 따로 분기할 수 있음

카카오 길찾기 기능&지도페이지 ui변경

---

src/api/productApi.js
src/api/storeApi.js
src/api/uploadApi.js

커밋 요약
기능 추가: 상품 등록 및 수정 시 이미지 업로드 기능 지원
임시 이미지 URL 제거: 임시 URL 사용을 제거하고 실제 이미지 URL을 사용하도록 개선
이미지 처리 로직 개선: 이미지 업로드 및 처리 로직을 최적화
API 호출 경로 수정: API 호출 경로를 최신화하여 일관성 유지

Feature: 이미지 업로드 구현

---

src/pages/MyPage.jsx

마이페이지에 프로필 카드부분 디자인을 수정하고 제로웨이스트 시각화자료를 추가하였습니다.
예약 확인 메뉴버튼을 추가하였습니다.
-Closes #150 
1. 마이페이지 프로필 카드 리디자인
2. 예약 확인 메뉴버튼 추가
로컬에서 확인하며 작업하였습니다.
예약확인 페이지와 예약확인 버튼 연결 필요

150 fe 마이페이지 디자인 및 예약 정보 확인 기능 추가

---

src/api/reservationApi.js
src/pages/UserReservationsPage.jsx
src/utils/dateUtils.js

사업자를 위한 예약 관리 기능을 추가하고,  예약 확인 페이지와 연동함  
사업자용 예약 관리 UI 구현 및 기능 점검 포함
1. `BusinessReservationPage.jsx` – 예약 목록/확정/거절 UI 구현
2. `UserReservationsPage.jsx` –  예약 내역 확인 페이지 연동
3. 관련 예약 API 로직 정리 및 UI 적용
- 관리자(사장님)용 예약 기능은 향후 알림 기능과 연계 예정

사업자페이지/예약페이지 정적페이지

---

src/pages/MapPage.jsx

지도에 카테고리를 추가하고 api와 연동하여 필터링이 수행되도록 했습니다.
이 외에 디자인 수정사항이 있습니다.
- Closes #154 
1. 카테고리 필터링 기능 추가
2. 메인페이지와 동일한 사이즈, placeholder 로 검색창 디자인 수정
3. 가게목록 전체보기/최소화 개선
로컬에서 테스트하며 진행하였습니다.

154 fe mappage category

---

src/App.jsx
src/api/productApi.js
src/api/reservationApi.js
src/api/reviewApi.js
src/components/products/ProductManagement.jsx
src/pages/BusinessPage.jsx
src/pages/EditStorePage.jsx
src/pages/StoreReservationsPage.jsx

기존 "상품" 중심의 페이지 명칭과 UI를 "럭키트" 중심으로 전면 개편함  
사용자와 사업자 모두에게 용어 통일성과 직관성을 제공하고자 전체 텍스트 및 기능 명칭을 럭키트 기반으로 변경
1. 페이지 제목을 "상품 관리" → "럭키트 관리"로 변경
2. 상단에 럭키트 소개 문구 추가  
- "럭키트는 랜덤 음식 패키지입니다. 한 가게당 하나만 등록할 수 있습니다."
3. 목록 항목에 "럭키트" 태그 표시 추가
4. 할인율 계산 로직 추가 및 UI에 표시
5. 전체 텍스트에서 "상품"이라는 단어를 "럭키트"로 변경
1. 사이드 메뉴 항목 "상품 정보 수정" → "럭키트 관리"로 변경
2. 콘솔 로그 등 관련 텍스트 모두 "럭키트"로 변경
1. 페이지 진입 시 제목 및 설명 정상 렌더링 확인
2. 등록된 럭키트 항목마다 할인율이 정확히 계산되어 표시되는지 확인
3. 사업자 페이지 메뉴 항목 클릭 시 정상 이동 여부 확인
4. 기존 상품 관련 기능들이 모두 "럭키트"로 잘 대체되었는지 확인
- 현재 럭키트는 가게당 하나만 등록 가능하도록 소개만 표시됨 (제한 기능은 추후 구현 가능)
- 할인율 계산은 판매가와 정가를 기준으로 수행되며, 부정확한 데이터에 대한 예외 처리는 추후 보완 예정

사업자 페이지 및 관련페이지 기능, 디자인수정

---

src/pages/HomePage.jsx

메인페이지 카테고리 필터링 api 연동했습니다.
- Closes #147 
1. 카테고리 id 값 정수로 설정
2. `/stores` api로 전체 가게 조회 후 클라이언트 사이드에서 필터링
없음
로컬에서 테스트하며 진행하였습니다.

147 fe mainpage category api

---

package.json
src/pages/StoreDetailPage.jsx

가게 상세 페이지의 디자인을 개선하고, 기능 흐름을 정비하여  
럭키트 상세정보 → 예약 → 예약 완료까지 매끄럽게 이어지도록 구현함
1. 가게 상세 페이지 디자인 개선
- 구성 요소 여백, 폰트, 정렬 등 시각적 정리
- 구분선, 제목 스타일 등 UI 요소 일관성 적용
2. 럭키트 정보 영역 개선
-  설명, 구성품 등을 보기 좋게 재배치
3. 예약 흐름 연결
- “럭키트 예약하기” 버튼 클릭 시 예약 페이지로 이동

가게 상세페이지 레이아웃변경 

---

src/pages/MyPage.jsx

마이페이지 연필모양 버튼 삭제하고 예약확인 페이지를 /reservation 에 연결했습니다.
- Closes #150 
1. 디자인 수정
로컬에서 확인하며 진행하였습니다.

style: 마이페이지 프로필 카드에서 수정 버튼 제거

---

src/context/AuthContext.jsx
src/pages/LoginPage.jsx
src/pages/SignupPage.jsx

로그인 및 회원가입 시 표시되는 오류 메시지를 사용자 입장에서 더 이해하기 쉽게 개선함
1. 너무 기술적인 에러 메시지를 자연어로 변경
- 예: "비밀번호 불일치" → "비밀번호가 일치하지 않아요"
- 예: "아이디 중복" → "이미 사용 중인 이메일이에요"
2. 필수 입력값 누락 시 친절한 안내 문구 표시
3. 서버 에러 발생 시도 "잠시 후 다시 시도해주세요"와 같은 안내로 처리
1. 잘못된 로그인 정보 입력 시 메시지 확인
2. 회원가입 조건 미충족 시 에러 메시지 확인
3. 네트워크 또는 서버 에러 시 메시지 출력 확인
- 향후 다국어 대응 시 메시지 분리 및 리소스 관리 필요

인증 관련 오류 메시지 사용자 친화적으로 개선

---

package.json
src/App.jsx
src/api/userApi.js
src/context/AuthContext.jsx
src/utils/apiMessages.js

로그인 및 회원가입 인증 흐름을 수정하고, 사용자 안내 메시지를 개선함  
회원가입하지 않은 계정으로도 로그인이 가능하던 문제를 해결하고, 안내 문구를 더 명확하게 수정함
1. 인증 로직 개선
- 회원가입하지 않은 계정으로 로그인 시 차단되도록 로직 수정
- 회원정보 조회 및 검증 과정 보완
2. 안내 메시지 수정
1. 존재하지 않는 이메일로 로그인 시 차단 메시지 출력 확인
2. 올바른 계정/비밀번호 입력 시 로그인 정상 진행 확인
3. 회원가입 성공/실패에 따른 메시지 확인
4. 브라우저 콘솔 오류 및 불필요한 로그 미출력 확인
- 향후 이메일 인증 또는 소셜 로그인 도입 시에도

로그인 검증 로직 개선 및 오류 메시지 수정

---

src/api/userApi.js
src/context/AuthContext.jsx
src/pages/LoginPage.jsx
src/pages/SignupPage.jsx
src/utils/apiMessages.js

로그인 및 회원가입 화면의 오류 메시지를 사용자 친화적으로 개선하고, 줄바꿈 적용 및 용어 정리를 통해 가독성을 높임  
기존 "세션"이라는 용어도 일반 사용자가 이해하기 쉬운 표현으로 변경함
1. 오류 메시지 표현 개선
- 기술 용어나 딱딱한 문구를 부드럽고 명확하게 수정
- 예: "세션 만료" → "로그인 시간이 만료되었어요. 다시 로그인해주세요"
2. 줄바꿈 적용
- 긴 메시지에 `\n` 또는 `<br />`을 적용하여 가독성 향상
3. 로그인/회원가입 공통 메시지 정리
- 이메일 또는 비밀번호 오류, 중복 계정 등 상황별 메시지 개선
1. 로그인 실패 시 메시지 확인 (비밀번호 오류, 미가입 계정 등)
2. 회원가입 조건 미충족 시 메시지 확인
3. 세션 만료 상태에서 메시지 출력 여부 확인
4. 줄바꿈 및 스타일이 화면에 자연스럽게 표시되는지 테스트
- 향후 메시지 다국어 대응이나 공통 상수화 시 고려 필요
- 긴 메시지는 두 줄 이상으로 나눠 사용자 혼동 줄이는 방향 유지

로그인 회원가입 권한및 문구수정

---

src/api/reservationApi.js
src/pages/MyPage.jsx
src/utils/ecoUtils.js

마이페이지에 환경 지표(아낀 금액, 절약한 CO2, 심은 나무)를 계산하여 시각화하는 기능을 추가함  
백엔드 응답 데이터 구조에 유연하게 대응하면서, 사용자에게 긍정적인 환경 영향을 직관적으로 보여주는 UI 구현
1. `MyPage.jsx`에 환경 지표 계산 로직 추가
- `originalPrice`, `discountPrice`, `quantity` 필드 기반으로 계산
- 필드가 없는 경우 `product` 객체에서 대체하거나 기본값 적용
2. 환경 지표 계산 결과를 UI에 출력
- 아낀 금액 (₩)
- 절약한 CO2 (kg)
- 심은 나무 수 (그루)
3. 린터 경고가 일부 존재하지만 기능 동작에는 영향 없음
1. 다양한 응답 데이터 구조에 대해 환경 지표가 정상 계산되는지 확인
2. UI에 아낀 금액 / CO2 / 나무 수치가 정확히 출력되는지 확인
3. 데이터가 일부 빠졌을 때 fallback 처리 및 기본값 적용 확인
4. 콘솔 오류 및 UI 레이아웃 이상 없는지 점검
- 추후 실제 환경 지표 계산식을 수정하거나, 아이콘 등 시각화 강화 가능성 있음
- 린터 경고는 다음 커밋에서 처리 예정

마이페이지 환경 지표 기능 구현

---

src/pages/BusinessPage.jsx
src/pages/StoreReservationsPage.jsx
src/utils/dateUtils.js

- 대기중예약, 가게예약목록에서 유저닉네임, 시간 보이도록 수정
-
크롬에서 테스트 완료

feat: 예약목록에서 닉네임, 시간 보이도록 수정

---

src/pages/UserReservationsPage.jsx

사용자 예약 목록 페이지를 실제 백엔드 API와 연동되도록 수정함  
임시 데이터 또는 하드코딩된 값 대신 서버에서 받아온 예약 데이터를 기반으로 UI를 렌더링함
1. `UserReservationsPage.jsx`에 백엔드 연동 로직 추가
- 예약 목록을 불러오는 API 호출(`GET /reservation/{user_id}`) 적용
- 응답 데이터 구조에 맞춰 리스트 렌더링 로직 수정
2. 예약 내역이 없을 경우 안내 문구 출력
3. 오류 발생 시 에러 메시지 또는 fallback 처리 추가
1. 예약 내역이 존재하는 사용자 계정으로 로그인 → 정상 렌더링 확인
2. 예약이 없는 계정 → 안내 메시지 출력 확인
3. 서버 오류, 응답 지연 등 상황에 대한 처리 확인
4. 모바일 및 데스크탑 화면에서 UI 정상 표시 확인
- 추후 예약 취소 기능 추가 시 현재 API 연동 구조를 그대로 확장 가능
- 예약 상태(확정/거절/대기)별 필터링 UI 도입도 고려됨

 사용자 예약 목록 페이지 백엔드 연동 수정

---

src/api/productApi.js
src/api/storeApi.js
src/components/products/ProductManagement.jsx
src/pages/EditStorePage.jsx

상품 상태 업데이트 및 삭제 기능 추가. 상품 관리 UI에서 유효기간 필드 제거 및 재고 수량 표시 방식 변경
가게 정보 수정 페이지에서 카테고리 및 운영시간 필드 추가
- Closes #164 
1. 상품 상태 업데이트 및 삭제 기능 추가
2. 상품 관리 UI에서 유효기간 필드 제거 및 재고 수량 표시 방식 변경
3. 가게 정보 수정 페이지에서 카테고리 및 운영시간 필드 추가
로컬에서 테스트

상품 상태 업데이트 및 삭제 기능 추가. 상품 관리 UI에서 유효기간 필드 제거 및 재고 수량 표시 방식 변경

---

src/components/products/ProductManagement.jsx
src/pages/EditStorePage.jsx

상품 및 가게 수정 페이지 유효성 검사 수정
- Closes #183
1. 상품 및 가게 수정 페이지 유효성 검사 수정
로컬에서 테스트

상품 및 가게 수정 페이지 유효성 검사 수정

---

src/api/storeApi.js
src/pages/StoreDetailPage.jsx

가게 상세조회 페이지에 럭키백(상품) 부분 api연동
(인데 이제 ... 머지가안되는..)
- #148 
1. `storeApi` 에 `getProductById` 추가
2. 하드코딩되어있던 럭키트 설명 부분 api 연동
3. 두 파일 모두 린트 오류 수정을 위한 `npx eslint --fix`
죄송합니다.............................................................

feat: 가게 상세 페이지 상품 조회 API 연동

---

src/api/reservationApi.js
src/api/userApi.js
src/pages/LoginPage.jsx

QA 테스트 및 배포 전 안정성 확보를 위해 불필요한 `console.log` 및 디버깅 주석을 삭제하거나 주석 처리함
1. `console.log`, `console.error`, `console.warn` 등 디버깅용 출력 제거 또는 주석 처리
2. 코드 중간에 남아있던 테스트용 주석, 임시 메시지 정리
3. QA 환경에서 로그 출력 없이 클린한 상태 유지
(별도 UI 변경 없음)
- 실제 서비스용 빌드 시에도 로그 출력이 없도록 ESLint 설정 또는 build 옵션 적용 예정

QA편의성을 위해 콘솔로그 삭제및 주석처리

---

src/components/map/StoreMarker.jsx
src/pages/MapPage.jsx
src/pages/UserReservationsPage.jsx

예약 취소 및 예약 조회 API 사용 방식의 일관성을 높이고,  
지도 페이지에서 좌표 없는 가게가 표시되지 않도록 마커 처리 로직을 개선함
1. **예약 취소 API 관련 수정**
- `cancelReservation` 함수 사용: 명확한 네이밍을 가진 고객용 예약 취소 전용 API
- 기존 `updateReservationStatus`는 상태 변경 전용이므로 승인/거절 용도로만 사용되도록 정리
- 코드 가독성과 API 목적의 일치성을 고려한 함수 교체
2. **사용자 예약 조회 API 수정**
- `getUserReservations` 함수에서 userId를 직접 전달하는 대신 `'me'` 사용
- 백엔드 API가 현재 로그인된 사용자 기준으로 동작하도록 설계되었기 때문
- `UserReservationsPage.jsx`에서 `user.id` 대신 `'me'` 문자열로 변경
3. **지도 마커 표시 관련 수정**
- 좌표값(`latitude`, `longitude`)이 없는 가게는 지도에 마커 표시하지 않도록 조건 처리
- 기존에는 랜덤 좌표를 생성했으나 이는 사용자 경험에 혼동을 줄 수 있음
- 실제 위치가 있는 가게만 지도에 노출되도록 개선
1. 사용자 예약 목록 확인 – `me` 사용 시 본인 예약 정상 출력 확인
2. 예약 취소 시 `cancelReservation` 함수가 정상 호출되고 취소 처리되는지 확인
3. 지도 페이지에서 좌표가 없는 가게가 마커로 표시되지 않는지 확인
4. 콘솔 오류, API 응답 에러 등 발생하지 않는지 점검
- 추후 …

예약 취소 api 수정, 지도 마커 수정

---

src/pages/StoreDetailPage.jsx
src/pages/UserReservationsPage.jsx

- 가게 상세 페이지에 예약 기능 추가 및 UI 개선. 
- 수량 조절, 제로웨이스트 옵션, 예약 처리 로직 구현. 
- 성공 모달 추가 및 예약 결과 표시 기능 추가.
- Resolves #148 
- [v] 코드가 정상적으로 컴파일되는지 확인했습니다.
- [v] 모든 테스트가 성공적으로 통과했습니다.
- [v] 관련 문서를 업데이트했습니다.
- [v] PR이 관련 이슈를 정확히 참조하고 있습니다.
- [v] 코드 스타일 가이드라인을 준수했습니다.
- [v] 코드 리뷰어를 지정했습니다.

feat: 가게 상세 페이지에 예약 기능 추가 및 UI 개선. 수량 조절, 제로웨이스트 옵션, 예약 처리 로직 구현. 성공 모달 추가 

---

src/api/reservationApi.js
src/pages/LoginPage.jsx

:로그인 페이지 수정
- Closes #191
로그인 페이지 수정
로컬에서 테스트

로그인 페이지 수정

---

src/pages/HomePage.jsx

메인 페이지의 카테고리 필터링 기능이 제대로 작동하지 않던 문제를 해결함  
서버 응답에 의존하던 기존 로직에서 클라이언트 측 필터링 로직을 추가하고, 가게 수 표시 및 스타일 오류도 함께 수정함
[FE] 메인페이지 가게 많을시 로딩 너무 오래걸림 #187
1. 클라이언트 측 카테고리 필터링 로직 추가
- `store.categoryId` 또는 `store.category`, `store.categories[0]` 등을 기준으로 유연하게 필터링
- 타입 불일치를 방지하기 위해 `String()`을 사용한 비교 적용
2. 가게 개수 표시 로직 수정
- 전체 가게 수가 아닌, 필터링된 결과의 개수를 기준으로 `setTotalStoreCount`에 반영
3. JSX 내 `<style>` 태그 오류 해결
- `dangerouslySetInnerHTML`을 사용하여 커스텀 스크롤바 숨김 스타일을 JSX 문법에 맞게 적용
4. 기존 무한 스크롤 및 할인 필터 기능은 영향 없이 그대로 유지
1. 카테고리 선택 시 해당 카테고리의 가게만 정확히 표시되는지 확인
2. 필터링된 가게 수가 상단에 정확히 반영되는지 확인
3. 무한 스크롤, 할인 필터와 병행 사용 시 기능 충돌 여부 확인
4. 스타일 태그 적용 여부 확인 (스크롤바 숨김 처리)

메인페이지 로딩 수정

---

src/api/storeApi.js

가게 업데이트 API에 카테고리 ID 추가
- Closes #195
가게 업데이트 API에 카테고리 ID 추가

가게 업데이트 API에 카테고리 ID 추가

---

src/pages/StoreDetailPage.jsx
src/pages/UserReservationsPage.jsx

- 가게 상세페이지: 상품 재고 표시
- 나의 예약 내역 페이지: 날짜 표기법 수정
- Resolves #194

feat: 상품 재고 표시 및 날짜표시 변경

---

src/pages/StoreDetailPage.jsx

- 닫힌 상품 예약 불가능
- 닫힌 상품 재고 숨김처리
- 닫힌 상품 블러처리
- Resolves #203 
크롬에서 테스트 완료

feat: 상품 예약 기능 개선 및 매진 상태 표시 추가

---

src/components/products/ProductManagement.jsx

상품 관리 UI 개선 및 버튼 스타일 변경
- Closes #205 
상품 관리 UI 개선 및 버튼 스타일 변경

상품 관리 UI 개선 및 버튼 스타일 변경

---

src/api/reservationApi.js
src/pages/LoginPage.jsx
src/pages/MyPage.jsx
src/pages/ReviewManagementPage.jsx
src/pages/UserReservationsPage.jsx

- 예약 정보 조회 로직 개선
- 환경 지표 계산 로직 수정 (주문 상품수로 게산)
- 리뷰 커밍순
- reservation/me 삭제
- Resolves #200
크롬에서 테스트 완료

feat: 사용자 예약 정보 조회 로직 개선 및 환경 지표 계산 방식 변경

---

src/pages/UserReservationsPage.jsx

(수정 후 다시 pr할 예정)
- reservationDate와 reservationTime 필드가 없는 경우에도 예약 정보를 정상적으로 표시하도록 수정
- 카드 클릭시 예약정보 표현
- Resolves #217 
크롬에서 테스트 완료

feat: 예약 페이지에서 가격 표시 방식 변경: 총 가격을 표시하도록 수정

---

src/pages/HomePage.jsx

홈 페이지 UI 정리 및 불필요한 정보/코드 제거 작업을 진행함  
- 메인 배너 클릭 시 가게 정렬 문제가 발생하던 이슈 해결  
- 가게 주소에 자동 포함되던 "대한민국" 문구 제거  
- 홈 페이지 내 불필요한 `console.log` 및 디버깅 로그 주석 처리
- Resolves #226
- Resolves #218
1. **메인 배너 클릭 시 정렬 문제 해결**
- 클릭 시 전체 가게가 아닌, 정렬 기준에 맞는 가게 목록만 보이도록 수정
2. **가게 주소에서 '대한민국' 제거**
- 백엔드 또는 프론트에서 자동으로 붙던 국가명 제거
- 주소가 중복되거나 어색하게 출력되던 문제 개선
3. **홈 페이지 콘솔 로그 정리**
- 모든 `console.log` 제거 또는 주석 처리
- QA 편의성과 프로덕션 품질 향상을 위한 불필요 로그 제거
1. 메인 배너 클릭 시 정렬된 결과만 표시되는지 확인
2. 가게 상세 및 리스트에서 '대한민국'이 제거된 주소 확인
3. 콘솔에 로그가 출력되지 않는지 확인
- 추후 주소는 국제화(i18n)를 고려하여 구성할 수 있음
- 로그 출력을 위한 dev-only 조건부 로깅 방식 도입 예정

홈페이지 관련 이슈해결(소팅, 콘솔로그 삭제, 가게 주소 형식 수정)

---

package.json
src/components/map/StoreMarker.jsx
src/pages/MapPage.jsx

지도에서 마커 클릭 시 인포윈도우가 제대로 표시되지 않던 문제를 해결함  
상태 업데이트 타이밍 및 선택 상태 판별 로직을 개선하여 일관되고 안정적인 인포윈도우 표시를 구현함
- Resolves #244
- Resolves #242
- Resolves #233
1. **상태 업데이트 순서 개선**
- `handleMarkerClick`에서 `setSelectedStoreId` → 약간의 지연 후 `setMapCenter` 호출  
- 인포윈도우가 먼저 뜬 뒤 지도가 이동되도록 타이밍 조절
2. **StoreMarker 컴포넌트 구조 개선**
- 내부 `showInfoWindow` 상태 제거  
- `isSelected` prop만을 기준으로 인포윈도우 표시 제어 → 상태 일관성 확보
3. **선택 상태 비교 로직 명확화**
- `selectedStoreId === store.id`  
- `selectedStoreId === \`${store.id}_force\``  
- `String(selectedStoreId).startsWith(store.id)`  
→ 다양한 ID 패턴에 대응하여 정확한 인포윈도우 제어
1. 마커 클릭 시 인포윈도우가 항상 정상 표시되는지 확인
2. 같은 마커를 반복 클릭해도 인포윈도우가 유지되는지 확인
3. 다른 마커 클릭 시 이전 인포윈도우가 닫히고 새 마커에만 표시되는지 확인
4. 지도 클릭 시 모든 인포윈도우가 닫히는지 확인
- 마커 클릭 처리의 타이밍 문제는 React의 상태 비동기 업데이트 특성으로 인해 발생할 수 있음
- 향후 selectedStoreId 관리가 더 …

지도페이지 큐에이 오류수정

---

src/pages/HomePage.jsx

지도에서 마커 클릭 시 인포윈도우가 표시되지 않던 문제와  
카테고리 필터링에서 잘못된 ID 매핑 문제를 함께 수정함
- Resolves #235
1. **마커 인포윈도우 표시 문제 해결**
- `handleMarkerClick`에서 상태 변경 순서 개선: `setSelectedStoreId` → 지연 후 `setMapCenter`
- `StoreMarker`에서 내부 상태 제거, `isSelected` prop만으로 제어
- ID 비교 로직을 명확히 정리하여 다양한 형식 대응
2. **카테고리 ID 연결 오류 수정**
- `categoryOptions` 내 ID와 실제 API/DB 기준 ID가 불일치했던 문제 수정
- 필터링 시 잘못된 ID로 인해 데이터가 올바르게 걸러지지 않던 문제 해결
```javascript
const categoryOptions = [
{ id: 'all', name: '전체', icon: '🔍' },
{ id: 1, name: '한식', icon: '🍚' },
{ id: 4, name: '일식', icon: '🍱' },
{ id: 2, name: '중식', icon: '🥢' },
{ id: 3, name: '양식', icon: '🍝' },
{ id: 5, name: '카페/베이커리', icon: '🍞' },
{ id: 6, name: '샐러드/청과', icon: '🥗' },
]

fix: 메인페이지 카테고리 ID 연결 수정

---

src/pages/EditProfilePage.jsx
src/pages/SignupPage.jsx

비밀번호 변경 기능에서 **입력 제약 조건 및 실시간 검증 로직**을 강화하여,  
보안성과 사용자 경험을 동시에 개선함
- Resolves #274
- Resolves #250
- Resolves #232
1. **대문자 입력 자동 소문자 변환**
- 모든 비밀번호 입력 필드에서 입력된 대문자를 자동으로 소문자로 변경하여 보안 일관성 확보
2. **공백 입력 차단**
- 비밀번호 입력 필드에 공백(스페이스)이 포함되지 않도록 입력 단계에서 즉시 제거
3. **현재 비밀번호와 새 비밀번호가 같은 경우 실시간 오류 처리**
- 입력 시점, 제출 시점 모두에서 비교 검증
- "새 비밀번호는 현재 비밀번호와 달라야 합니다" 메시지 표시
4. **비밀번호 확인 필드 개선**
- 빈 값 및 불일치 시 각각에 대한 구체적인 피드백 제공
- 입력이 완료되었고 일치하면 성공 메시지(녹색) 표시
5. **헬퍼 텍스트 및 시각적 피드백 개선**
- 각 상태별 동적인 메시지 (회색 안내 / 빨간 오류 / 초록 성공)
- 입력 필드 테두리 색상 변경
6. **API 응답 처리 강화**
- 비밀번호 불일치 또는 기타 오류 메시지 사용자에게 정확히 전달
- 성공 시 필드 초기화 및 홈 이동, 토스트 메시지 표시
1. 대문자 입력 시 자동 소문자 변환 확인
2. 공백 입력 시 무시 처리되는지 확인
3. 현재/새 비밀번호 동일 → 오류 메시지 표시 여부 확인
4. 비밀번호 확인 일치/불일치 → 피드백 정확성 확인
5. API 실패/성공 응답에 따른 상태 처리 및 메시지 표시 확인
- 향후 비밀번호 강도 검사(특수문자 포함, 반복 문자 …

feat: 입력 유효성 검사 개선 - 비밀번호 소문자 변환 및 공백 제거

---

src/api/apiClient.js

한국 시간대 설정 및 응답 데이터의 시간 필드 변환 기능 추가
- Closes #219
1. 한국 시간대 설정 및 응답 데이터의 시간 필드 변환 기능 추가
\
로컬에서 테스트

한국 시간대 설정 및 응답 데이터의 시간 필드 변환 기능 추가

---

src/components/products/ProductManagement.jsx

럭키트 등록/수정 시 패키지 설명 필드의 유효성 검사를 개선하여 사용자 경험을 향상시켰습니다. 
설명 필드가 10글자 미만일 때 실시간으로 피드백을 제공하도록 구현했습니다.
- Resolves #263
1. 패키지 설명 필드 유효성 검사 로직 개선
- 설명 필드가 비어있거나 10글자 미만일 때 에러 메시지 표시
- 실시간 유효성 검사를 통해 즉각적인 피드백 제공
2. 에러 메시지 UI 개선
- 설명 필드 아래에 빨간색 텍스트로 에러 메시지 표시
- 유효성 검사 실패 시 테두리 색상 변경
1. 패키지 설명 필드 테스트
- 빈 설명 입력 시 에러 메시지 표시 확인
- 10글자 미만 입력 시 에러 메시지 표시 확인
- 10글자 이상 입력 시 에러 메시지 사라짐 확인
2. 폼 제출 테스트
- 유효하지 않은 설명으로 제출 시도 시 폼 제출 방지 확인
- 유효한 설명으로 제출 시 정상 작동 확인
3. UI 테스트
- 에러 메시지 스타일 및 위치 확인
- 테두리 색상 변경 확인
유효성 검사는 클라이언트 사이드에서만 수행되며, 서버 API 요청은 발생하지 않습니다.
사용자 경험을 위해 실시간 피드백을 제공하도록 구현했습니다.
**이전 PR(270-럭키트저장실패토스트메시지 관련)과 동일한 페이지 수정사항이나 dev 브랜치를 당겨와서 여기서는 여전히 토스트메시지가 모달 뒤쪽으로 뜹니다..**

feat: 럭키트 설명 필드 유효성 검사 개선

---

src/components/products/ProductManagement.jsx
src/pages/StoreDetailPage.jsx

- 재고 수량 입력 기능 개선
- 재고 수량을 자유롭게 지우고 입력할 수 있도록 수정
- +/- 버튼으로 재고 수량 조절 가능
- 재고가 0이거나 비어있을 때 감소 버튼(-) 비활성화
- 재고 수량이 비어있을 때 저장 불가능하도록 유효성 검사 추가
- 가격 입력 필드 개선
- 입력 필드 타입을 number로 변경하여 숫자만 입력 가능하도록 수정
- 가격 입력 필드 오른쪽에 "원" 단위 표시 추가
- 100원 이상 1천만원 이하 유효성 검사 추가
- 가격 범위를 벗어날 경우 에러 메시지 표시
- 상품 정보 표시 개선
- 재고가 0일 때도 정확하게 표시
- 재고 수량에 따른 버튼 상태 관리 개선
- 매진 상태일 때 버튼 비활성화 및 텍스트 변경
- 예약 성공 후 "계속 둘러보기" 클릭 시 페이지 새로고침 추가
- Resolves #282 
- Resolves #251 
- Resolves #247 
- Resolves #220
크롬에서 테스트 완료

[QA] 재고 감소 조건 수정, 재고 직접 입력 처리 추가, 폼 유효성 검사 강화 및 가격 입력 필드 개선

---

src/components/products/ProductManagement.jsx
src/pages/BusinessPage.jsx
src/pages/StoreDetailPage.jsx

src/components/products/ProductManagement.jsx
- 상품 가격 표시 UI 개선
- 할인율 표시 로직 수정 (최대 99%로 제한)
src/pages/BusinessPage.jsx
- "내 정보 수정" 버튼 추가 
src/pages/StoreDetailPage.jsx
- 할인율 표시 로직 수정 (최대 99%로 제한)
가게 기본 정보 UI 전면 개선
- 새로운 카드 스타일 레이아웃 적용
- 아이콘과 함께 정보 표시 방식 변경
- 영업시간 표시 방식 개선
- Resolves #240 
- Resolves #265 
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]

사업자도 정보 수정 가능하도록 수정 및 UI개선

---

src/components/map/StoreMarker.jsx
src/pages/MapPage.jsx

지도 페이지에서 다음과 같은 UI/UX 문제를 해결하고 개선함  
- 클러스터링 조정으로 마커 겹침 최소화  
- 인포윈도우가 마커 클릭 시 제대로 표시되지 않던 오류 수정  
- 슬라이딩 패널 동작 오류(열리거나 닫히지 않던 문제) 수정
- Resolves #238
1. **클러스터링 세기 조절**
- 마커 밀집 시 지나치게 하나로 묶이던 현상 완화
- 클러스터링 기준 거리 및 레벨 조건 수정
2. **인포윈도우 표시 오류 수정**
- 마커 클릭 시 `selectedStoreId`와 `store.id` 비교 로직 강화
- `InfoWindow` 조건부 렌더링 및 위치 설정 로직 개선
3. **슬라이딩 패널 오류 수정**
- `storeListOpen` 상태와 마커/지도 이벤트 간 충돌 해결
- 스크롤 시 열리고, 지도 클릭 시 닫히는 동작 정상화

283 bug 지도 페이지 이슈

---

src/components/map/StoreMarker.jsx
src/pages/MapPage.jsx

지도 페이지에서 다음과 같은 UI/UX 문제와 디버깅 로그를 정리함  
- 클러스터링 조건 개선으로 마커 겹침 최소화  
- 인포윈도우 표시 오류 수정  
- 슬라이딩 패널 열림/닫힘 동작 오류 수정  
- 콘솔 로그 제거로 QA 및 프로덕션 환경 정리
**불필요한 콘솔 로그 삭제**
- 개발 중 사용된 `console.log` 제거
- 프로덕션 환경에서 불필요한 디버깅 메시지 출력 방지

지도페이지 콘솔로그 삭제

---

src/api/productApi.js
src/api/uploadApi.js
src/config/apiConfig.js
src/pages/HomePage.jsx
src/pages/MapPage.jsx

- 메인페이지 및 맵페이지에서 가게정보를 dev서버에서 받아오던 오류 해결
크롬에서 테스트 완료

API 엔드포인트 수정 및 이미지 업로드 로직 개선: 상품 목록 조회 API 경로 변경

---

src/App.jsx
src/context/AuthContext.jsx
src/pages/EditProfilePage.jsx
src/pages/NotFoundPage.jsx
src/utils/apiMessages.js

url로 접근 시 유령 페이지가 보여지는 이슈 & 회원탈퇴시 오류 수정
- Closes #261 
- Closes #266
1. 다른 url 접근시 404 not found 창이 뜨도록 수정
2. 회웥탈퇴시 alert 창 수정

 url로 접근 시 유령 페이지가 보여지는 이슈 & 회원탈퇴시 오류 수정

---

src/api/apiClient.js
src/api/categoryApi.js
src/api/productApi.js
src/api/reservationApi.js
src/api/reviewApi.js
src/api/storeApi.js
src/api/uploadApi.js
src/api/userApi.js
src/utils/apiMessages.js
src/utils/dateUtils.js
src/utils/jwtUtils.js

개발자 도구의 콘솔 로그를 정리하고, API 클라이언트 설정을 개선하여  
보안성과 사용자 경험을 높이고 axios 관련 코드 일관성을 강화한 PR입니다.
- Resolves #301
1. **apiClient 설정 개선**
- `withCredentials: true` 설정으로 CORS 요청 시 인증 정보 전송 활성화
- `'X-Timezone'` 헤더 활성화 → 서버에 한국 시간대 정보 전송
- 불필요한 CORS 관련 헤더 제거
- 모든 `console.log`, `console.error`, `console.warn` 제거
2. **api 파일 정리 및 개선**
- `storeApi.js`, `userApi.js`, `productApi.js`, `reservationApi.js`, `uploadApi.js`, `reviewApi.js`, `categoryApi.js`
- 모든 콘솔 로그 제거
- 사용하지 않는 import 제거
- 기존 `axios` 직접 호출 → `apiClient`로 통일
3. **유틸리티 파일 정리**
- `apiMessages.js`, `jwtUtils.js`, `dateUtils.js` 내 콘솔 로그 제거
해당 사항 없음 (코드 구조 및 콘솔 출력 관련 변경)
- 모든 API 정상 호출 여부 확인 (`axios` → `apiClient` 변경된 파일들)
- 콘솔 로그가 사라졌는지 개발자 도구에서 확인
- CORS 요청 시 쿠키 및 인증 정보 포함됨 확인
- 서버에서 시간대 정보 수신되는지 로그 확인
- 콘솔에 불필요하게 출력되던 디버깅 정보 제거로 사용자 및 운영 환경에서 …

301 fe 개발자도구

---

src/pages/HomePage.jsx

- 백앤드 페이지네이션과 연동 10개씩 가져오도록 구현
- Resolves #305

feat: 메인페이지 페이지네이션 추가

---

src/pages/HomePage.jsx

필터 및 정렬 기능을 api로 백앤드에서 수행하도록 변경
- Resolves #316

feat: 필터 및 정렬 백앤드로 이관

---

src/api/storeApi.js
src/components/map/MapController.jsx
src/components/map/StoreMarker.jsx
src/pages/MapPage.jsx

- 홈 및 지도 페이지에서의 가게 목록 조회 및 정렬 방식 개선
- 지도 컨트롤러 버튼에 이벤트 전파 차단 적용
- 사용자 위치 기반 정렬 동작 개선 및 위치 권한 요청 로직 추가
- 클라이언트 사이드 정렬/필터링 제거 → 백엔드 API 파라미터 중심으로 정리
- StoreMarker 클릭 이벤트 및 인포윈도우 전파 문제 해결
- `URLSearchParams`로 파라미터 정리
- `isDiscountOpen` 등 파라미터 분리 처리 → 전체 URL 구조 개선
- `params`로 넘기던 이전 방식 제거 → URL로만 파라미터 처리
- 클라이언트에서 하던 정렬/검색/카테고리 필터 모두 제거
- 서버에 `sort`, `lat`, `lng`, `storeName`, `categoryId` 등 쿼리 파라미터 전달
- `가까운 순` 선택 시 위치 권한 미획득 상태면 `getUserLocation()` 실행 → 위치 기반 정렬 수행
- `navigator.geolocation`으로 권한 요청
- 최초 권한 획득 이후 상태값(`locationPermissionRequested`)을 기억하여 불필요한 재요청 방지
- 확대/축소/현재 위치 버튼에 `stopPropagation()` 및 `preventDefault()` 처리 추가
- `onClick(store)` 호출 시 `setTimeout` 사용 → 이벤트 전파 문제 방지
- `event._stopPropagation`, `event.nativeEvent.stopPropagation()` 등 전파 제어 강화
- 줌 변경 시 중심 좌표 보존
- 현재 위치 이동 시 위치 …

지도페이지 기능 개선: API 경로 수정, 위치기능 버그 수정, 마감할인 필터 개선, 확대/축소 기능 수정

---

src/components/Search/SearchBar.jsx
src/pages/HomePage.jsx

- 검색 기능 프론트에서 백앤드 api를 사용하도록 수정
- HomePage 컴포넌트에서는 debounce 기능을 적용하여 연속된 타이핑 동안 지나치게 많은 API 호출이 발생하지 않도록 구현
- 디바운스 시간은 300ms로 설정하여 사용자가 타이핑을 멈추면 약 0.3초 후에 검색 결과가 나타나도록 구현
- Resolves #319 
크롬에서 테스트 완료

feat: 319 가게명검색기능 백앤드 연동

---

src/pages/HomePage.jsx

세션스토리지를 이용하여 새로고침시에도 필터 및 정렬옵션이 유지되도록 구현
- closes #325

feat: 새로고침시 필터 및 정렬 조건 유지

---

src/pages/HomePage.jsx

리뷰 순 정렬 쿼리 rating -> review로 수정 
- closes #347 
크롬에서 테스트완료

feat: 정렬 review 추가

---

src/pages/StoreDetailPage.jsx

가게 상세페이지에서 리뷰 평점 표시 방식 개선 및 상품 정보 섹션 제거
- Closes #350 
1. 가게 상세 페이지에서 리뷰에서 상품 금액및 수량 제거
2. 별점 표시 별 추가
로컬에서 테스트

가게상세페이지에서 리뷰 평점 표시 방식 개선 및 상품 정보 섹션 제거

---

src/context/AuthContext.jsx
src/pages/EditProfilePage.jsx

닉네임 및 비밀번호 업데이트 로직 간소화, 성공 메시지 표시 방식 변경 및 비밀번호 입력 안내 문구 수정
- Closes #355
- Closes #341
1. 닉네임 및 비밀번호 수정 시 멘트 변경
로컬에서 테스트

닉네임 및 비밀번호 업데이트 로직 간소화, 성공 메시지 표시 방식 변경 및 비밀번호 입력 안내 문구 수정

---

.gitignore
src/api/storeApi.js
src/api/uploadApi.js
src/pages/ReviewManagementPage.jsx

프로젝트의 이미지 업로드 로직을 개선하여 클라이언트에서 S3로 직접 이미지를 업로드하는 Presigned URL 방식을 구현했음
이를 통해 백엔드 서버 부하를 줄이고 업로드 속도와 안정성을 향상시켰음
[주요 변경사항]
1. 업로드 방식 변경
- 기존: 클라이언트 → 백엔드 서버 → S3 방식의 이미지 업로드
- 개선: Presigned URL을 이용한 클라이언트 → S3 직접 업로드 방식
2. 업로드 프로세스 개선
- 백엔드에서 Presigned URL 발급 요청
- 발급받은 URL을 통해 S3에 직접 이미지 업로드
- 업로드 완료 후 CloudFront URL 생성
3. 이미지 접근성 향상
- S3 업로드 시 'x-amz-acl: public-read' 헤더 추가하여 공개 접근 가능하도록 설정
- CloudFront URL을 통한 안정적인 이미지 제공
4. 기대 효과
- 백엔드 서버 부하 감소
- 이미지 업로드 속도 향상
- 안정적인 이미지 저장 및 제공
- 클라이언트-서버 간 데이터 전송량 감소
- closes #354 
크롬에서 테스트 완료

이미지 업로드 방식 개선 PR: Presigned URL 방식 도입

---

src/pages/HomePage.jsx

홈페이지 스크롤안되던 이슈해결
카테고리 글씨 크기 수정

홈페이지 카테고리 버튼 텍스트 크기 조정 및 스크롤 수정

---

.releaserc.json

semantic-release 설정을 수정하여 beta 버전과 함께 patch/minor 버전도 함께 올라가도록 개선했습니다. 이를 통해 버전 관리의 정확성과 추적성이 향상될 것으로 기대됩니다.
- Resolves #362
1. `.releaserc.json` 파일의 dev 브랜치 설정 수정
- `"prerelease": "beta"` → `"prerelease": true`
- `"channel": "beta"` 추가
2. beta 버전과 함께 patch/minor 버전도 함께 증가하도록 설정
- feat 커밋 시: `1.0.0-beta.1` → `1.1.0-beta.1`
- fix 커밋 시: `1.1.0-beta.1` → `1.1.1-beta.1`
1. dry-run 모드로 semantic-release 테스트 실행
2. 커밋 분석 결과 확인
- feat 커밋: minor 버전 증가 확인
- fix 커밋: patch 버전 증가 확인
3. beta 버전과 정식 버전이 함께 올라가는지 확인
이 변경으로 인해 기존 태그들은 모두 삭제되었으며, 다음 커밋부터 새로운 버전 관리 체계가 적용될 예정입니다.

fix: semantic-release 설정 수정 - beta 버전과 함께 patch/minor 버전도 올라가도록 변경

---

src/pages/MyPage.jsx

마이페이지의 UI를 개선하여 사용자 경험을 향상시켰습니다. 프로필 카드의 불필요한 제목을 제거하고, 환경 기여 섹션의 텍스트를 간소화하여 더 깔끔한 디자인을 구현했습니다.
- Resolves #366
1. 프로필 카드 섹션에서 '내 정보' 제목 제거
2. 환경 기여 섹션의 설명 텍스트 간소화 ("럭키트를 통해 음식물 쓰레기를 줄이고 환경을 보호하고 있어요!" → "럭키트를 통해 쓰레기를 줄이고 환경을 보호하고 있어요!")
3. 환경 기여 섹션의 레이아웃 및 여백 조정
변경 전:
- 프로필 카드와 환경 기여 섹션에 동일한 정보가 중복으로 노출됨
- 환경 기여 섹션의 설명 텍스트가 더 길었음
변경 후:
- 프로필 카드가 더 깔끔해짐
- 환경 기여 섹션의 설명이 간결해짐
1. 마이페이지 접속 시 프로필 카드와 환경 기여 섹션이 정상적으로 표시되는지 확인
2. 환경 기여 섹션의 텍스트가 가독성 있게 표시되는지 확인
이 PR은 UI 개선에 초점을 맞추었으며, 기능적인 변경사항은 없습니다. 디자인 일관성과 사용자 경험 향상을 위해 텍스트와 레이아웃을 최적화했습니다.

style: 마이페이지 UI 개선

---

src/api/apiClient.js
src/api/reservationApi.js
src/api/storeApi.js
src/api/uploadApi.js
src/api/userApi.js
src/context/AuthContext.jsx
src/pages/EditProfilePage.jsx
src/pages/UserReservationsPage.jsx
src/utils/jwtUtils.js

로컬 스토리지에서 세션 스토리지로 토큰 및 사용자 정보 저장 방식 변경

fix: 로컬 스토리지에서 세션 스토리지로 토큰 및 사용자 정보 저장 방식 변경
